use sqlx::PgPool;

pub async fn run(pool: &PgPool) -> anyhow::Result<()> {
    let op_id: Option<(uuid::Uuid,)> =
        sqlx::query_as("SELECT id FROM operators WHERE email = 'admin@tundra.local' LIMIT 1")
            .fetch_optional(pool)
            .await?;

    let Some((op_id,)) = op_id else {
        println!("  skipped — no admin operator (run operators seeder first)");
        return Ok(());
    };

    // (name, metric, condition, threshold, duration_secs, severity, scope_type)
    let rules: &[(&str, &str, &str, f64, i32, &str, &str)] = &[
        // ── Global server rules ───────────────────────────────────────────────
        (
            "High CPU (global)",
            "cpu_pct",
            "gt",
            90.0,
            300,
            "critical",
            "global",
        ),
        (
            "Elevated CPU (global)",
            "cpu_pct",
            "gt",
            80.0,
            600,
            "warning",
            "global",
        ),
        (
            "Low CPU idle (global)",
            "cpu_idle_pct",
            "lt",
            10.0,
            300,
            "warning",
            "global",
        ),
        (
            "Disk critical (global)",
            "disk_used_pct",
            "gt",
            95.0,
            60,
            "critical",
            "global",
        ),
        (
            "Disk warning (global)",
            "disk_used_pct",
            "gt",
            80.0,
            300,
            "warning",
            "global",
        ),
        (
            "Memory critical (global)",
            "mem_used_pct",
            "gt",
            95.0,
            120,
            "critical",
            "global",
        ),
        (
            "Memory high (global)",
            "mem_used_pct",
            "gt",
            85.0,
            300,
            "warning",
            "global",
        ),
        (
            "Swap in use (global)",
            "swap_used_pct",
            "gt",
            50.0,
            600,
            "warning",
            "global",
        ),
        (
            "Swap critical (global)",
            "swap_used_pct",
            "gt",
            90.0,
            300,
            "critical",
            "global",
        ),
        (
            "Load avg high (global)",
            "load_avg_1m",
            "gt",
            8.0,
            300,
            "warning",
            "global",
        ),
        (
            "Load avg critical (global)",
            "load_avg_1m",
            "gt",
            16.0,
            120,
            "critical",
            "global",
        ),
        (
            "Inode exhaustion (global)",
            "inode_used_pct",
            "gt",
            90.0,
            300,
            "warning",
            "global",
        ),
        // ── Network ───────────────────────────────────────────────────────────
        (
            "High inbound bandwidth",
            "net_rx_mbps",
            "gt",
            900.0,
            120,
            "warning",
            "global",
        ),
        (
            "High outbound bandwidth",
            "net_tx_mbps",
            "gt",
            900.0,
            120,
            "warning",
            "global",
        ),
        (
            "Packet loss detected",
            "net_packet_loss_pct",
            "gt",
            1.0,
            120,
            "warning",
            "global",
        ),
        (
            "High packet loss",
            "net_packet_loss_pct",
            "gt",
            5.0,
            60,
            "critical",
            "global",
        ),
        (
            "TCP connection saturation",
            "tcp_conn_count",
            "gt",
            50000.0,
            300,
            "warning",
            "global",
        ),
        (
            "Network errors high",
            "net_error_rate",
            "gt",
            0.01,
            300,
            "warning",
            "global",
        ),
        // ── Disk I/O ──────────────────────────────────────────────────────────
        (
            "Disk I/O wait high",
            "disk_io_wait_pct",
            "gt",
            20.0,
            300,
            "warning",
            "global",
        ),
        (
            "Disk I/O wait critical",
            "disk_io_wait_pct",
            "gt",
            40.0,
            120,
            "critical",
            "global",
        ),
        (
            "Disk read latency high",
            "disk_read_latency_ms",
            "gt",
            50.0,
            300,
            "warning",
            "global",
        ),
        (
            "Disk write latency high",
            "disk_write_latency_ms",
            "gt",
            100.0,
            300,
            "warning",
            "global",
        ),
        // ── Process / runtime ─────────────────────────────────────────────────
        (
            "Process count high",
            "proc_count",
            "gt",
            800.0,
            300,
            "warning",
            "global",
        ),
        (
            "Zombie processes",
            "proc_zombie_count",
            "gt",
            5.0,
            600,
            "warning",
            "global",
        ),
        (
            "File descriptor exhaustion",
            "fd_used_pct",
            "gt",
            90.0,
            300,
            "warning",
            "global",
        ),
        // ── Server-scope rules ────────────────────────────────────────────────
        (
            "CPU spike — server",
            "cpu_pct",
            "gt",
            95.0,
            60,
            "critical",
            "server",
        ),
        (
            "Memory OOM risk",
            "mem_used_pct",
            "gt",
            98.0,
            60,
            "critical",
            "server",
        ),
        (
            "Root disk filling fast",
            "disk_used_pct",
            "gt",
            90.0,
            180,
            "critical",
            "server",
        ),
        (
            "Agent not responding",
            "agent_heartbeat_age_secs",
            "gt",
            120.0,
            120,
            "critical",
            "server",
        ),
        (
            "Server offline",
            "agent_heartbeat_age_secs",
            "gt",
            300.0,
            60,
            "critical",
            "server",
        ),
        (
            "CPU throttling",
            "cpu_throttle_pct",
            "gt",
            30.0,
            300,
            "warning",
            "server",
        ),
        (
            "Memory page faults high",
            "mem_pgfault_rate",
            "gt",
            1000.0,
            300,
            "warning",
            "server",
        ),
        (
            "High context switches",
            "ctx_switch_rate",
            "gt",
            200000.0,
            300,
            "warning",
            "server",
        ),
        (
            "Temperature critical",
            "temp_cpu_celsius",
            "gt",
            85.0,
            60,
            "critical",
            "server",
        ),
        (
            "Temperature warning",
            "temp_cpu_celsius",
            "gt",
            75.0,
            300,
            "warning",
            "server",
        ),
        // ── Site-scope rules ──────────────────────────────────────────────────
        (
            "Site error rate high",
            "http_5xx_rate",
            "gt",
            5.0,
            120,
            "warning",
            "site",
        ),
        (
            "Site error rate critical",
            "http_5xx_rate",
            "gt",
            20.0,
            60,
            "critical",
            "site",
        ),
        (
            "Site p95 latency high",
            "http_p95_ms",
            "gt",
            2000.0,
            300,
            "warning",
            "site",
        ),
        (
            "Site p99 latency critical",
            "http_p99_ms",
            "gt",
            5000.0,
            120,
            "critical",
            "site",
        ),
        (
            "Site requests/sec spike",
            "http_req_per_sec",
            "gt",
            10000.0,
            120,
            "warning",
            "site",
        ),
        (
            "Site 4xx rate elevated",
            "http_4xx_rate",
            "gt",
            10.0,
            300,
            "warning",
            "site",
        ),
        (
            "SSL cert expiry — 30d",
            "ssl_days_remaining",
            "lt",
            30.0,
            300,
            "warning",
            "site",
        ),
        (
            "SSL cert expiry — 7d",
            "ssl_days_remaining",
            "lt",
            7.0,
            300,
            "critical",
            "site",
        ),
        (
            "SSL cert expiry — 1d",
            "ssl_days_remaining",
            "lt",
            1.0,
            60,
            "critical",
            "site",
        ),
        (
            "Site down (health check)",
            "health_check_up",
            "lt",
            1.0,
            60,
            "critical",
            "site",
        ),
        (
            "Site slow health check",
            "health_check_ms",
            "gt",
            3000.0,
            120,
            "warning",
            "site",
        ),
        (
            "Static asset cache miss",
            "cache_miss_rate",
            "gt",
            50.0,
            600,
            "warning",
            "site",
        ),
        (
            "Session count spike",
            "active_sessions",
            "gt",
            100000.0,
            300,
            "warning",
            "site",
        ),
        (
            "Bandwidth usage high",
            "bandwidth_mbps",
            "gt",
            800.0,
            300,
            "warning",
            "site",
        ),
        (
            "PHP-FPM queue backlog",
            "phpfpm_listen_queue",
            "gt",
            50.0,
            120,
            "warning",
            "site",
        ),
        (
            "PHP-FPM process saturation",
            "phpfpm_active_pct",
            "gt",
            90.0,
            120,
            "critical",
            "site",
        ),
    ];

    for (name, metric, condition, threshold, duration_secs, severity, scope_type) in rules {
        sqlx::query(
            "INSERT INTO alert_rules \
               (name, scope_type, metric, condition, threshold, duration_secs, severity, created_by) \
             VALUES ($1, $2, $3, $4, $5, $6, $7, $8) ON CONFLICT DO NOTHING",
        )
        .bind(name)
        .bind(scope_type)
        .bind(metric)
        .bind(condition)
        .bind(threshold)
        .bind(duration_secs)
        .bind(severity)
        .bind(op_id)
        .execute(pool)
        .await?;
        println!("  alert rule \"{name}\"");
    }
    Ok(())
}
