use sqlx::PgPool;

pub async fn run(pool: &PgPool) -> anyhow::Result<()> {
    // (apex, dns_managed_by)  — "tundra" | "registrar" | "external"
    let rows: &[(&str, &str)] = &[
        // ── Sites already seeded (tundra-managed) ────────────────────────────
        ("acme-corp.io", "tundra"),
        ("nexusplatform.com", "tundra"),
        ("orbitanalytics.io", "tundra"),
        ("sparkcommerce.store", "tundra"),
        ("prismdesign.co", "tundra"),
        ("forgedevtools.dev", "tundra"),
        ("velashipping.com", "tundra"),
        ("crestfinance.app", "tundra"),
        ("novamedia.studio", "tundra"),
        ("bloombotanicals.com", "tundra"),
        ("summitoutdoor.co", "tundra"),
        ("urbanthreads.shop", "tundra"),
        ("pearljewellery.store", "tundra"),
        ("rustichome.co", "tundra"),
        ("coastalsurf.shop", "tundra"),
        ("pixelagency.design", "tundra"),
        ("arcstudio.xyz", "tundra"),
        ("memocreative.com", "tundra"),
        ("lumedigital.agency", "tundra"),
        ("canvasworks.art", "tundra"),
        ("codeflow.dev", "tundra"),
        ("stackr.io", "tundra"),
        ("devhub.tools", "tundra"),
        ("patchwork.dev", "tundra"),
        ("relayci.io", "tundra"),
        ("meditrack.health", "tundra"),
        ("wellpath.care", "tundra"),
        ("fitpulse.app", "tundra"),
        ("zenmind.co", "tundra"),
        ("clearrx.pharmacy", "tundra"),
        ("learnloop.edu", "tundra"),
        ("academiq.io", "tundra"),
        ("tutorbase.com", "tundra"),
        ("skillbridge.training", "tundra"),
        ("quizlab.online", "tundra"),
        ("thedailywire.press", "tundra"),
        ("epochmagazine.com", "tundra"),
        ("broadcastnow.tv", "tundra"),
        ("podcastcentral.fm", "tundra"),
        ("pixelpress.pub", "tundra"),
        ("vaultfinance.io", "tundra"),
        ("paybridge.finance", "tundra"),
        ("tokenledger.co", "tundra"),
        ("clearbooks.accountancy", "tundra"),
        ("wealthgraph.app", "tundra"),
        ("roamtravel.com", "tundra"),
        ("stayeasy.rentals", "tundra"),
        ("horizonhotels.co", "tundra"),
        ("voyageplanner.travel", "tundra"),
        ("atlastours.guide", "tundra"),
        ("foodrun.delivery", "tundra"),
        ("saffronkitchen.com", "tundra"),
        ("bentobox.food", "tundra"),
        ("harvesttable.co", "tundra"),
        ("quickbite.app", "tundra"),
        ("nestfinder.properties", "tundra"),
        ("proptrack.io", "tundra"),
        ("keystonerealty.com", "tundra"),
        ("urbanloft.rent", "tundra"),
        ("spaceshare.co", "tundra"),
        ("swiftlog.logistics", "tundra"),
        ("cargonow.io", "tundra"),
        ("routemaster.delivery", "tundra"),
        ("packflow.supply", "tundra"),
        ("freightwise.global", "tundra"),
        ("talentcore.hr", "tundra"),
        ("peopleos.app", "tundra"),
        ("hireflow.io", "tundra"),
        ("shiftsync.works", "tundra"),
        ("payrollnow.co", "tundra"),
        ("smartnest.io", "tundra"),
        ("iotify.cloud", "tundra"),
        ("sensornet.dev", "tundra"),
        ("gridwatch.energy", "tundra"),
        ("autohome.systems", "tundra"),
        ("vaultguard.security", "tundra"),
        ("penscope.io", "tundra"),
        ("shieldai.tech", "tundra"),
        ("trustlink.net", "tundra"),
        ("ciphervault.co", "tundra"),
        ("leadpulse.marketing", "tundra"),
        ("campaignkit.io", "tundra"),
        ("reachmore.email", "tundra"),
        ("brandbeat.co", "tundra"),
        ("funnellabs.growth", "tundra"),
        ("pixelvaultgames.com", "tundra"),
        ("gamecraft.gg", "tundra"),
        ("levelupstudios.games", "tundra"),
        ("arenanet.online", "tundra"),
        ("questbridge.co", "tundra"),
        ("neuralbase.ai", "tundra"),
        ("infercore.ml", "tundra"),
        ("datamind.io", "tundra"),
        ("cognify.ai", "tundra"),
        ("modelhub.tech", "tundra"),
        // ── External registrar-managed domains ───────────────────────────────
        ("globalventures.com", "registrar"),
        ("techcatalyst.io", "registrar"),
        ("alphastream.net", "registrar"),
        ("betalaunch.co", "registrar"),
        ("deltaops.cloud", "registrar"),
        ("epsilonworks.com", "registrar"),
        ("zetacore.dev", "registrar"),
        ("etaplatform.io", "registrar"),
        ("thetashift.co", "registrar"),
        ("iotadesign.studio", "registrar"),
        ("kappagrowth.com", "registrar"),
        ("lambdatech.net", "registrar"),
        ("muanalytics.io", "registrar"),
        ("nubusiness.co", "registrar"),
        ("xisolutions.com", "registrar"),
        ("omicronservices.net", "registrar"),
        ("pinetwork.io", "registrar"),
        ("rhosystems.tech", "registrar"),
        ("sigmainfra.cloud", "registrar"),
        ("tauplatform.co", "registrar"),
        ("upsilonlabs.com", "registrar"),
        ("phidynamic.io", "registrar"),
        ("chiventures.co", "registrar"),
        ("psisoftware.net", "registrar"),
        ("omegastack.com", "registrar"),
        ("apexbuilds.io", "registrar"),
        ("bridgelabs.co", "registrar"),
        ("corelogix.com", "registrar"),
        ("deepnodes.io", "registrar"),
        ("echoworks.net", "registrar"),
        // ── External DNS (third-party nameservers) ───────────────────────────
        ("fluxdevops.com", "external"),
        ("gritanalytics.io", "external"),
        ("hubcreations.co", "external"),
        ("infrabyte.net", "external"),
        ("jumpworks.dev", "external"),
        ("keynodeservices.com", "external"),
        ("leanscale.io", "external"),
        ("meshnet.co", "external"),
        ("novascale.cloud", "external"),
        ("orbitaltech.io", "external"),
        ("peaklabs.co", "external"),
        ("quantumleap.dev", "external"),
        ("rampgrowth.com", "external"),
        ("sprintcloud.io", "external"),
        ("torquesystems.net", "external"),
        ("unitecorp.co", "external"),
        ("vividplatforms.com", "external"),
        ("wavepath.io", "external"),
        ("xenonlabs.dev", "external"),
        ("yellowbrick.co", "external"),
        ("zephyrhosting.net", "external"),
        ("agileworks.io", "external"),
        ("blockbuilt.co", "external"),
        ("cloudcraft.dev", "external"),
        ("drivemedia.com", "external"),
        ("enrichlabs.io", "external"),
        ("focuspro.co", "external"),
        ("gleamtech.net", "external"),
        ("healthbridge.io", "external"),
        ("impulsedev.co", "external"),
        ("jointhub.com", "external"),
        ("kineticdata.io", "external"),
        ("launchpad.dev", "external"),
        ("mintanalytics.co", "external"),
        ("networkiq.com", "external"),
        ("openlooplabs.io", "external"),
        ("parallaxtech.co", "external"),
        ("quicktop.io", "external"),
        ("realtime.systems", "external"),
        ("scalepoint.co", "external"),
        ("trackwise.io", "external"),
        ("unified.cloud", "external"),
        ("vaultworks.co", "external"),
        ("wireframe.dev", "external"),
        ("xenixcloud.io", "external"),
        ("yellowhive.co", "external"),
        ("zirconlabs.net", "external"),
        ("absolutetech.io", "external"),
        ("bridgepoint.co", "external"),
        ("cloudnest.dev", "external"),
        ("datastitch.io", "external"),
        ("edgecloud.co", "external"),
        ("flowstudio.dev", "external"),
        ("gridtech.io", "external"),
        ("hivecloud.co", "external"),
        ("infinite.systems", "external"),
        ("joltworks.io", "external"),
        ("keepstack.co", "external"),
        ("looplabs.dev", "external"),
        ("motiontech.io", "external"),
        ("nodebase.co", "external"),
        ("omnilabs.io", "external"),
        ("portkey.dev", "external"),
        ("quickshift.co", "external"),
        ("raycloud.io", "external"),
        ("solidops.co", "external"),
        ("teleport.systems", "external"),
        ("upperstack.io", "external"),
        ("vectorbase.co", "external"),
        ("warptech.dev", "external"),
        ("xtend.io", "external"),
        ("yieldops.co", "external"),
        ("zonetech.io", "external"),
    ];

    for (apex, dns_managed_by) in rows {
        sqlx::query(
            "INSERT INTO domains (apex, dns_managed_by) \
             VALUES ($1, $2) ON CONFLICT (apex) DO NOTHING",
        )
        .bind(apex)
        .bind(dns_managed_by)
        .execute(pool)
        .await?;
        println!("  domain {apex} ({dns_managed_by})");
    }
    Ok(())
}
