/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthWordpressRouteImport } from './routes/_auth.wordpress'
import { Route as AuthTemplatesRouteImport } from './routes/_auth.templates'
import { Route as AuthSitesRouteImport } from './routes/_auth.sites'
import { Route as AuthSettingsRouteImport } from './routes/_auth.settings'
import { Route as AuthServersRouteImport } from './routes/_auth.servers'
import { Route as AuthScheduledTasksRouteImport } from './routes/_auth.scheduled-tasks'
import { Route as AuthPluginsRouteImport } from './routes/_auth.plugins'
import { Route as AuthOperatorsRouteImport } from './routes/_auth.operators'
import { Route as AuthMailRouteImport } from './routes/_auth.mail'
import { Route as AuthDomainsRouteImport } from './routes/_auth.domains'
import { Route as AuthDatabasesRouteImport } from './routes/_auth.databases'
import { Route as AuthDatabaseServersRouteImport } from './routes/_auth.database-servers'
import { Route as AuthDashboardRouteImport } from './routes/_auth.dashboard'
import { Route as AuthDaemonsRouteImport } from './routes/_auth.daemons'
import { Route as AuthBackupsRouteImport } from './routes/_auth.backups'
import { Route as AuthAuditLogRouteImport } from './routes/_auth.audit-log'
import { Route as AuthAlertsRouteImport } from './routes/_auth.alerts'
import { Route as AuthWordpressIndexRouteImport } from './routes/_auth.wordpress.index'
import { Route as AuthSitesIndexRouteImport } from './routes/_auth.sites.index'
import { Route as AuthServersIndexRouteImport } from './routes/_auth.servers.index'
import { Route as AuthPluginsIndexRouteImport } from './routes/_auth.plugins.index'
import { Route as AuthWordpressInstallIdRouteImport } from './routes/_auth.wordpress.$installId'
import { Route as AuthWordpressInstallIdIndexRouteImport } from './routes/_auth.wordpress.$installId.index'
import { Route as AuthWordpressInstallIdPluginsRouteImport } from './routes/_auth.wordpress.$installId.plugins'
import { Route as AuthWordpressInstallIdThemesRouteImport } from './routes/_auth.wordpress.$installId.themes'
import { Route as AuthWordpressInstallIdDatabaseRouteImport } from './routes/_auth.wordpress.$installId.database'
import { Route as AuthWordpressInstallIdSecurityRouteImport } from './routes/_auth.wordpress.$installId.security'
import { Route as AuthWordpressInstallIdUsersRouteImport } from './routes/_auth.wordpress.$installId.users'
import { Route as AuthWordpressInstallIdBackupsRouteImport } from './routes/_auth.wordpress.$installId.backups'
import { Route as AuthWordpressInstallIdSettingsRouteImport } from './routes/_auth.wordpress.$installId.settings'
import { Route as AuthWordpressInstallIdStagingRouteImport } from './routes/_auth.wordpress.$installId.staging'
import { Route as AuthWordpressInstallIdDangerRouteImport } from './routes/_auth.wordpress.$installId.danger'
import { Route as AuthSitesNewRouteImport } from './routes/_auth.sites.new'
import { Route as AuthSitesSiteIdRouteImport } from './routes/_auth.sites.$siteId'
import { Route as AuthSitesSiteIdIndexRouteImport } from './routes/_auth.sites.$siteId.index'
import { Route as AuthSitesSiteIdDeploymentsRouteImport } from './routes/_auth.sites.$siteId.deployments'
import { Route as AuthSitesSiteIdDomainsRouteImport } from './routes/_auth.sites.$siteId.domains'
import { Route as AuthSitesSiteIdSslRouteImport } from './routes/_auth.sites.$siteId.ssl'
import { Route as AuthSitesSiteIdDatabasesRouteImport } from './routes/_auth.sites.$siteId.databases'
import { Route as AuthSitesSiteIdDaemonsRouteImport } from './routes/_auth.sites.$siteId.daemons'
import { Route as AuthSitesSiteIdCronRouteImport } from './routes/_auth.sites.$siteId.cron'
import { Route as AuthSitesSiteIdLogsRouteImport } from './routes/_auth.sites.$siteId.logs'
import { Route as AuthSitesSiteIdSettingsRouteImport } from './routes/_auth.sites.$siteId.settings'
import { Route as AuthSitesSiteIdDangerRouteImport } from './routes/_auth.sites.$siteId.danger'
import { Route as AuthSitesSiteIdBackupsRouteImport } from './routes/_auth.sites.$siteId.backups'
import { Route as AuthSitesSiteIdDnsRouteImport } from './routes/_auth.sites.$siteId.dns'
import { Route as AuthSitesSiteIdPhpRouteImport } from './routes/_auth.sites.$siteId.php'
import { Route as AuthSitesSiteIdFilesRouteImport } from './routes/_auth.sites.$siteId.files'
import { Route as AuthSitesSiteIdEmailRouteImport } from './routes/_auth.sites.$siteId.email'
import { Route as AuthSitesSiteIdAnalyticsRouteImport } from './routes/_auth.sites.$siteId.analytics'
import { Route as AuthFilesRouteImport } from './routes/_auth.files'
import { Route as AuthFilesIndexRouteImport } from './routes/_auth.files.index'
import { Route as AuthFilesSiteIdRouteImport } from './routes/_auth.files.$siteId'
import { Route as AuthEditorSiteIdRouteImport } from './routes/_auth.editor.$siteId'
import { Route as AuthToolsPhpMyAdminRouteImport } from './routes/_auth.tools.phpmyadmin'
import { Route as AuthSettingsSecurityRouteImport } from './routes/_auth.settings.security'
import { Route as AuthSettingsMcpRouteImport } from './routes/_auth.settings.mcp'
import { Route as AuthSettingsProfileRouteImport } from './routes/_auth.settings.profile'
import { Route as AuthSettingsGeneralRouteImport } from './routes/_auth.settings.general'
import { Route as AuthSettingsSmtpRouteImport } from './routes/_auth.settings.smtp'
import { Route as AuthSettingsNotificationsRouteImport } from './routes/_auth.settings.notifications'
import { Route as AuthSettingsAccessRouteImport } from './routes/_auth.settings.access'
import { Route as AuthSettingsStorageRouteImport } from './routes/_auth.settings.storage'
import { Route as AuthSettingsBrandingRouteImport } from './routes/_auth.settings.branding'
import { Route as AuthSettingsDnsRouteImport } from './routes/_auth.settings.dns'
import { Route as AuthSettingsDefaultsRouteImport } from './routes/_auth.settings.defaults'
import { Route as AuthSettingsSecurityPolicyRouteImport } from './routes/_auth.settings.security-policy'
import { Route as AuthServersNewRouteImport } from './routes/_auth.servers.new'
import { Route as AuthServersServerIdRouteImport } from './routes/_auth.servers.$serverId'
import { Route as AuthPluginsPluginIdRouteImport } from './routes/_auth.plugins.$pluginId'
import { Route as AuthMailQueueRouteImport } from './routes/_auth.mail.queue'
import { Route as AuthMailMailboxesRouteImport } from './routes/_auth.mail.mailboxes'
import { Route as AuthMailDomainsRouteImport } from './routes/_auth.mail.domains'
import { Route as AuthDomainsIndexRouteImport } from './routes/_auth.domains.index'
import { Route as AuthDomainsNewRouteImport } from './routes/_auth.domains.new'
import { Route as AuthDomainsDomainIdRouteImport } from './routes/_auth.domains.$domainId'
import { Route as AuthDatabasesNewRouteImport } from './routes/_auth.databases.new'
import { Route as AuthDatabasesDatabaseIdRouteImport } from './routes/_auth.databases.$databaseId'
import { Route as AuthDatabaseServersNewRouteImport } from './routes/_auth.database-servers.new'
import { Route as AuthDatabaseServersServerIdRouteImport } from './routes/_auth.database-servers.$serverId'
import { Route as AuthBackupsTargetsRouteImport } from './routes/_auth.backups.targets'
import { Route as AuthBackupsSnapshotsRouteImport } from './routes/_auth.backups.snapshots'
import { Route as AuthBackupsJobsRouteImport } from './routes/_auth.backups.jobs'
import { Route as AuthServersServerIdMaintenanceRouteImport } from './routes/_auth.servers.$serverId.maintenance'
import { Route as AuthMailDomainsNewRouteImport } from './routes/_auth.mail.domains.new'
import { Route as AuthMailDomainsMailDomainIdRouteImport } from './routes/_auth.mail.domains.$mailDomainId'
import { Route as AuthBackupsTargetsNewRouteImport } from './routes/_auth.backups.targets.new'
import { Route as AuthBackupsJobsNewRouteImport } from './routes/_auth.backups.jobs.new'
import { Route as AuthMailDomainsMailDomainIdDiagnosticsRouteImport } from './routes/_auth.mail.domains.$mailDomainId.diagnostics'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthWordpressRoute = AuthWordpressRouteImport.update({
  id: '/wordpress',
  path: '/wordpress',
  getParentRoute: () => AuthRoute,
} as any)
const AuthTemplatesRoute = AuthTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSitesRoute = AuthSitesRouteImport.update({
  id: '/sites',
  path: '/sites',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSettingsRoute = AuthSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthRoute,
} as any)
const AuthServersRoute = AuthServersRouteImport.update({
  id: '/servers',
  path: '/servers',
  getParentRoute: () => AuthRoute,
} as any)
const AuthScheduledTasksRoute = AuthScheduledTasksRouteImport.update({
  id: '/scheduled-tasks',
  path: '/scheduled-tasks',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPluginsRoute = AuthPluginsRouteImport.update({
  id: '/plugins',
  path: '/plugins',
  getParentRoute: () => AuthRoute,
} as any)
const AuthOperatorsRoute = AuthOperatorsRouteImport.update({
  id: '/operators',
  path: '/operators',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMailRoute = AuthMailRouteImport.update({
  id: '/mail',
  path: '/mail',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDomainsRoute = AuthDomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDatabasesRoute = AuthDatabasesRouteImport.update({
  id: '/databases',
  path: '/databases',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDatabaseServersRoute = AuthDatabaseServersRouteImport.update({
  id: '/database-servers',
  path: '/database-servers',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDaemonsRoute = AuthDaemonsRouteImport.update({
  id: '/daemons',
  path: '/daemons',
  getParentRoute: () => AuthRoute,
} as any)
const AuthBackupsRoute = AuthBackupsRouteImport.update({
  id: '/backups',
  path: '/backups',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAuditLogRoute = AuthAuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAlertsRoute = AuthAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AuthRoute,
} as any)
const AuthWordpressIndexRoute = AuthWordpressIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthWordpressRoute,
} as any)
const AuthSitesIndexRoute = AuthSitesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthSitesRoute,
} as any)
const AuthServersIndexRoute = AuthServersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthServersRoute,
} as any)
const AuthPluginsIndexRoute = AuthPluginsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthPluginsRoute,
} as any)
const AuthWordpressInstallIdRoute = AuthWordpressInstallIdRouteImport.update({
  id: '/$installId',
  path: '/$installId',
  getParentRoute: () => AuthWordpressRoute,
} as any)
const AuthWordpressInstallIdIndexRoute = AuthWordpressInstallIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthWordpressInstallIdRoute,
} as any)
const AuthWordpressInstallIdPluginsRoute = AuthWordpressInstallIdPluginsRouteImport.update({
  id: '/plugins',
  path: '/plugins',
  getParentRoute: () => AuthWordpressInstallIdRoute,
} as any)
const AuthWordpressInstallIdThemesRoute = AuthWordpressInstallIdThemesRouteImport.update({
  id: '/themes',
  path: '/themes',
  getParentRoute: () => AuthWordpressInstallIdRoute,
} as any)
const AuthWordpressInstallIdDatabaseRoute = AuthWordpressInstallIdDatabaseRouteImport.update({
  id: '/database',
  path: '/database',
  getParentRoute: () => AuthWordpressInstallIdRoute,
} as any)
const AuthWordpressInstallIdSecurityRoute = AuthWordpressInstallIdSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AuthWordpressInstallIdRoute,
} as any)
const AuthWordpressInstallIdUsersRoute = AuthWordpressInstallIdUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthWordpressInstallIdRoute,
} as any)
const AuthWordpressInstallIdBackupsRoute = AuthWordpressInstallIdBackupsRouteImport.update({
  id: '/backups',
  path: '/backups',
  getParentRoute: () => AuthWordpressInstallIdRoute,
} as any)
const AuthWordpressInstallIdSettingsRoute = AuthWordpressInstallIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthWordpressInstallIdRoute,
} as any)
const AuthWordpressInstallIdStagingRoute = AuthWordpressInstallIdStagingRouteImport.update({
  id: '/staging',
  path: '/staging',
  getParentRoute: () => AuthWordpressInstallIdRoute,
} as any)
const AuthWordpressInstallIdDangerRoute = AuthWordpressInstallIdDangerRouteImport.update({
  id: '/danger',
  path: '/danger',
  getParentRoute: () => AuthWordpressInstallIdRoute,
} as any)
const AuthSitesNewRoute = AuthSitesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthSitesRoute,
} as any)
const AuthSitesSiteIdRoute = AuthSitesSiteIdRouteImport.update({
  id: '/$siteId',
  path: '/$siteId',
  getParentRoute: () => AuthSitesRoute,
} as any)
const AuthSitesSiteIdIndexRoute = AuthSitesSiteIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthSitesSiteIdRoute,
} as any)
const AuthSitesSiteIdDeploymentsRoute = AuthSitesSiteIdDeploymentsRouteImport.update({
  id: '/deployments',
  path: '/deployments',
  getParentRoute: () => AuthSitesSiteIdRoute,
} as any)
const AuthSitesSiteIdDomainsRoute = AuthSitesSiteIdDomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => AuthSitesSiteIdRoute,
} as any)
const AuthSitesSiteIdSslRoute = AuthSitesSiteIdSslRouteImport.update({
  id: '/ssl',
  path: '/ssl',
  getParentRoute: () => AuthSitesSiteIdRoute,
} as any)
const AuthSitesSiteIdDatabasesRoute = AuthSitesSiteIdDatabasesRouteImport.update({
  id: '/databases',
  path: '/databases',
  getParentRoute: () => AuthSitesSiteIdRoute,
} as any)
const AuthSitesSiteIdDaemonsRoute = AuthSitesSiteIdDaemonsRouteImport.update({
  id: '/daemons',
  path: '/daemons',
  getParentRoute: () => AuthSitesSiteIdRoute,
} as any)
const AuthSitesSiteIdCronRoute = AuthSitesSiteIdCronRouteImport.update({
  id: '/cron',
  path: '/cron',
  getParentRoute: () => AuthSitesSiteIdRoute,
} as any)
const AuthSitesSiteIdLogsRoute = AuthSitesSiteIdLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AuthSitesSiteIdRoute,
} as any)
const AuthSitesSiteIdSettingsRoute = AuthSitesSiteIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthSitesSiteIdRoute,
} as any)
const AuthSitesSiteIdDangerRoute = AuthSitesSiteIdDangerRouteImport.update({
  id: '/danger',
  path: '/danger',
  getParentRoute: () => AuthSitesSiteIdRoute,
} as any)
const AuthSitesSiteIdBackupsRoute = AuthSitesSiteIdBackupsRouteImport.update({
  id: '/backups',
  path: '/backups',
  getParentRoute: () => AuthSitesSiteIdRoute,
} as any)
const AuthSitesSiteIdDnsRoute = AuthSitesSiteIdDnsRouteImport.update({
  id: '/dns',
  path: '/dns',
  getParentRoute: () => AuthSitesSiteIdRoute,
} as any)
const AuthSitesSiteIdPhpRoute = AuthSitesSiteIdPhpRouteImport.update({
  id: '/php',
  path: '/php',
  getParentRoute: () => AuthSitesSiteIdRoute,
} as any)
const AuthSitesSiteIdFilesRoute = AuthSitesSiteIdFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => AuthSitesSiteIdRoute,
} as any)
const AuthSitesSiteIdEmailRoute = AuthSitesSiteIdEmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => AuthSitesSiteIdRoute,
} as any)
const AuthSitesSiteIdAnalyticsRoute = AuthSitesSiteIdAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthSitesSiteIdRoute,
} as any)
const AuthEditorSiteIdRoute = AuthEditorSiteIdRouteImport.update({
  id: '/editor/$siteId',
  path: '/editor/$siteId',
  getParentRoute: () => AuthRoute,
} as any)
const AuthFilesRoute = AuthFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => AuthRoute,
} as any)
const AuthToolsPhpMyAdminRoute = AuthToolsPhpMyAdminRouteImport.update({
  id: '/tools/phpmyadmin',
  path: '/tools/phpmyadmin',
  getParentRoute: () => AuthRoute,
} as any)
const AuthFilesIndexRoute = AuthFilesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthFilesRoute,
} as any)
const AuthFilesSiteIdRoute = AuthFilesSiteIdRouteImport.update({
  id: '/$siteId',
  path: '/$siteId',
  getParentRoute: () => AuthFilesRoute,
} as any)
const AuthSettingsProfileRoute = AuthSettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthSettingsRoute,
} as any)
const AuthSettingsSecurityRoute = AuthSettingsSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AuthSettingsRoute,
} as any)
const AuthSettingsMcpRoute = AuthSettingsMcpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => AuthSettingsRoute,
} as any)
const AuthSettingsGeneralRoute = AuthSettingsGeneralRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => AuthSettingsRoute,
} as any)
const AuthSettingsSmtpRoute = AuthSettingsSmtpRouteImport.update({
  id: '/smtp',
  path: '/smtp',
  getParentRoute: () => AuthSettingsRoute,
} as any)
const AuthSettingsNotificationsRoute = AuthSettingsNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AuthSettingsRoute,
} as any)
const AuthSettingsAccessRoute = AuthSettingsAccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => AuthSettingsRoute,
} as any)
const AuthSettingsStorageRoute = AuthSettingsStorageRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => AuthSettingsRoute,
} as any)
const AuthSettingsBrandingRoute = AuthSettingsBrandingRouteImport.update({
  id: '/branding',
  path: '/branding',
  getParentRoute: () => AuthSettingsRoute,
} as any)
const AuthSettingsDnsRoute = AuthSettingsDnsRouteImport.update({
  id: '/dns',
  path: '/dns',
  getParentRoute: () => AuthSettingsRoute,
} as any)
const AuthSettingsDefaultsRoute = AuthSettingsDefaultsRouteImport.update({
  id: '/defaults',
  path: '/defaults',
  getParentRoute: () => AuthSettingsRoute,
} as any)
const AuthSettingsSecurityPolicyRoute = AuthSettingsSecurityPolicyRouteImport.update({
  id: '/security-policy',
  path: '/security-policy',
  getParentRoute: () => AuthSettingsRoute,
} as any)
const AuthServersNewRoute = AuthServersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthServersRoute,
} as any)
const AuthServersServerIdRoute = AuthServersServerIdRouteImport.update({
  id: '/$serverId',
  path: '/$serverId',
  getParentRoute: () => AuthServersRoute,
} as any)
const AuthPluginsPluginIdRoute = AuthPluginsPluginIdRouteImport.update({
  id: '/$pluginId',
  path: '/$pluginId',
  getParentRoute: () => AuthPluginsRoute,
} as any)
const AuthMailQueueRoute = AuthMailQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => AuthMailRoute,
} as any)
const AuthMailMailboxesRoute = AuthMailMailboxesRouteImport.update({
  id: '/mailboxes',
  path: '/mailboxes',
  getParentRoute: () => AuthMailRoute,
} as any)
const AuthMailDomainsRoute = AuthMailDomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => AuthMailRoute,
} as any)
const AuthDomainsIndexRoute = AuthDomainsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthDomainsRoute,
} as any)
const AuthDomainsNewRoute = AuthDomainsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthDomainsRoute,
} as any)
const AuthDomainsDomainIdRoute = AuthDomainsDomainIdRouteImport.update({
  id: '/$domainId',
  path: '/$domainId',
  getParentRoute: () => AuthDomainsRoute,
} as any)
const AuthDatabasesNewRoute = AuthDatabasesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthDatabasesRoute,
} as any)
const AuthDatabasesDatabaseIdRoute = AuthDatabasesDatabaseIdRouteImport.update({
  id: '/$databaseId',
  path: '/$databaseId',
  getParentRoute: () => AuthDatabasesRoute,
} as any)
const AuthDatabaseServersNewRoute = AuthDatabaseServersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthDatabaseServersRoute,
} as any)
const AuthDatabaseServersServerIdRoute =
  AuthDatabaseServersServerIdRouteImport.update({
    id: '/$serverId',
    path: '/$serverId',
    getParentRoute: () => AuthDatabaseServersRoute,
  } as any)
const AuthBackupsTargetsRoute = AuthBackupsTargetsRouteImport.update({
  id: '/targets',
  path: '/targets',
  getParentRoute: () => AuthBackupsRoute,
} as any)
const AuthBackupsSnapshotsRoute = AuthBackupsSnapshotsRouteImport.update({
  id: '/snapshots',
  path: '/snapshots',
  getParentRoute: () => AuthBackupsRoute,
} as any)
const AuthBackupsJobsRoute = AuthBackupsJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AuthBackupsRoute,
} as any)
const AuthServersServerIdMaintenanceRoute =
  AuthServersServerIdMaintenanceRouteImport.update({
    id: '/maintenance',
    path: '/maintenance',
    getParentRoute: () => AuthServersServerIdRoute,
  } as any)
const AuthMailDomainsNewRoute = AuthMailDomainsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthMailDomainsRoute,
} as any)
const AuthMailDomainsMailDomainIdRoute =
  AuthMailDomainsMailDomainIdRouteImport.update({
    id: '/$mailDomainId',
    path: '/$mailDomainId',
    getParentRoute: () => AuthMailDomainsRoute,
  } as any)
const AuthBackupsTargetsNewRoute = AuthBackupsTargetsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthBackupsTargetsRoute,
} as any)
const AuthBackupsJobsNewRoute = AuthBackupsJobsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthBackupsJobsRoute,
} as any)
const AuthMailDomainsMailDomainIdDiagnosticsRoute =
  AuthMailDomainsMailDomainIdDiagnosticsRouteImport.update({
    id: '/diagnostics',
    path: '/diagnostics',
    getParentRoute: () => AuthMailDomainsMailDomainIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/alerts': typeof AuthAlertsRoute
  '/audit-log': typeof AuthAuditLogRoute
  '/backups': typeof AuthBackupsRouteWithChildren
  '/daemons': typeof AuthDaemonsRoute
  '/dashboard': typeof AuthDashboardRoute
  '/database-servers': typeof AuthDatabaseServersRouteWithChildren
  '/databases': typeof AuthDatabasesRouteWithChildren
  '/domains': typeof AuthDomainsRouteWithChildren
  '/mail': typeof AuthMailRouteWithChildren
  '/operators': typeof AuthOperatorsRoute
  '/plugins': typeof AuthPluginsRouteWithChildren
  '/scheduled-tasks': typeof AuthScheduledTasksRoute
  '/servers': typeof AuthServersRouteWithChildren
  '/settings': typeof AuthSettingsRouteWithChildren
  '/sites': typeof AuthSitesRouteWithChildren
  '/templates': typeof AuthTemplatesRoute
  '/wordpress': typeof AuthWordpressRouteWithChildren
  '/backups/jobs': typeof AuthBackupsJobsRouteWithChildren
  '/backups/snapshots': typeof AuthBackupsSnapshotsRoute
  '/backups/targets': typeof AuthBackupsTargetsRouteWithChildren
  '/database-servers/$serverId': typeof AuthDatabaseServersServerIdRoute
  '/database-servers/new': typeof AuthDatabaseServersNewRoute
  '/databases/$databaseId': typeof AuthDatabasesDatabaseIdRoute
  '/databases/new': typeof AuthDatabasesNewRoute
  '/domains/': typeof AuthDomainsIndexRoute
  '/domains/$domainId': typeof AuthDomainsDomainIdRoute
  '/domains/new': typeof AuthDomainsNewRoute
  '/mail/domains': typeof AuthMailDomainsRouteWithChildren
  '/mail/mailboxes': typeof AuthMailMailboxesRoute
  '/mail/queue': typeof AuthMailQueueRoute
  '/plugins/$pluginId': typeof AuthPluginsPluginIdRoute
  '/servers/$serverId': typeof AuthServersServerIdRouteWithChildren
  '/servers/new': typeof AuthServersNewRoute
  '/settings/mcp': typeof AuthSettingsMcpRoute
  '/settings/security': typeof AuthSettingsSecurityRoute
  '/settings/profile': typeof AuthSettingsProfileRoute
  '/settings/general': typeof AuthSettingsGeneralRoute
  '/settings/smtp': typeof AuthSettingsSmtpRoute
  '/settings/notifications': typeof AuthSettingsNotificationsRoute
  '/settings/access': typeof AuthSettingsAccessRoute
  '/settings/storage': typeof AuthSettingsStorageRoute
  '/settings/branding': typeof AuthSettingsBrandingRoute
  '/settings/dns': typeof AuthSettingsDnsRoute
  '/settings/defaults': typeof AuthSettingsDefaultsRoute
  '/settings/security-policy': typeof AuthSettingsSecurityPolicyRoute
  '/sites/$siteId': typeof AuthSitesSiteIdRouteWithChildren
  '/sites/new': typeof AuthSitesNewRoute
  '/wordpress/$installId': typeof AuthWordpressInstallIdRouteWithChildren
  '/plugins/': typeof AuthPluginsIndexRoute
  '/sites/$siteId/': typeof AuthSitesSiteIdIndexRoute
  '/sites/$siteId/deployments': typeof AuthSitesSiteIdDeploymentsRoute
  '/sites/$siteId/domains': typeof AuthSitesSiteIdDomainsRoute
  '/sites/$siteId/ssl': typeof AuthSitesSiteIdSslRoute
  '/sites/$siteId/databases': typeof AuthSitesSiteIdDatabasesRoute
  '/sites/$siteId/daemons': typeof AuthSitesSiteIdDaemonsRoute
  '/sites/$siteId/cron': typeof AuthSitesSiteIdCronRoute
  '/sites/$siteId/logs': typeof AuthSitesSiteIdLogsRoute
  '/sites/$siteId/settings': typeof AuthSitesSiteIdSettingsRoute
  '/sites/$siteId/danger': typeof AuthSitesSiteIdDangerRoute
  '/sites/$siteId/backups': typeof AuthSitesSiteIdBackupsRoute
  '/sites/$siteId/dns': typeof AuthSitesSiteIdDnsRoute
  '/sites/$siteId/php': typeof AuthSitesSiteIdPhpRoute
  '/sites/$siteId/files': typeof AuthSitesSiteIdFilesRoute
  '/sites/$siteId/email': typeof AuthSitesSiteIdEmailRoute
  '/sites/$siteId/analytics': typeof AuthSitesSiteIdAnalyticsRoute
  '/files': typeof AuthFilesRouteWithChildren
  '/files/': typeof AuthFilesIndexRoute
  '/files/$siteId': typeof AuthFilesSiteIdRoute
  '/editor/$siteId': typeof AuthEditorSiteIdRoute
  '/tools/phpmyadmin': typeof AuthToolsPhpMyAdminRoute
  '/servers/': typeof AuthServersIndexRoute
  '/sites/': typeof AuthSitesIndexRoute
  '/wordpress/': typeof AuthWordpressIndexRoute
  '/wordpress/$installId/': typeof AuthWordpressInstallIdIndexRoute
  '/wordpress/$installId/plugins': typeof AuthWordpressInstallIdPluginsRoute
  '/wordpress/$installId/themes': typeof AuthWordpressInstallIdThemesRoute
  '/wordpress/$installId/database': typeof AuthWordpressInstallIdDatabaseRoute
  '/wordpress/$installId/security': typeof AuthWordpressInstallIdSecurityRoute
  '/wordpress/$installId/users': typeof AuthWordpressInstallIdUsersRoute
  '/wordpress/$installId/backups': typeof AuthWordpressInstallIdBackupsRoute
  '/wordpress/$installId/settings': typeof AuthWordpressInstallIdSettingsRoute
  '/wordpress/$installId/staging': typeof AuthWordpressInstallIdStagingRoute
  '/wordpress/$installId/danger': typeof AuthWordpressInstallIdDangerRoute
  '/backups/jobs/new': typeof AuthBackupsJobsNewRoute
  '/backups/targets/new': typeof AuthBackupsTargetsNewRoute
  '/mail/domains/$mailDomainId': typeof AuthMailDomainsMailDomainIdRouteWithChildren
  '/mail/domains/new': typeof AuthMailDomainsNewRoute
  '/servers/$serverId/maintenance': typeof AuthServersServerIdMaintenanceRoute
  '/mail/domains/$mailDomainId/diagnostics': typeof AuthMailDomainsMailDomainIdDiagnosticsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/alerts': typeof AuthAlertsRoute
  '/audit-log': typeof AuthAuditLogRoute
  '/backups': typeof AuthBackupsRouteWithChildren
  '/daemons': typeof AuthDaemonsRoute
  '/dashboard': typeof AuthDashboardRoute
  '/database-servers': typeof AuthDatabaseServersRouteWithChildren
  '/databases': typeof AuthDatabasesRouteWithChildren
  '/domains': typeof AuthDomainsRouteWithChildren
  '/mail': typeof AuthMailRouteWithChildren
  '/operators': typeof AuthOperatorsRoute
  '/scheduled-tasks': typeof AuthScheduledTasksRoute
  '/settings': typeof AuthSettingsRouteWithChildren
  '/templates': typeof AuthTemplatesRoute
  '/backups/jobs': typeof AuthBackupsJobsRouteWithChildren
  '/backups/snapshots': typeof AuthBackupsSnapshotsRoute
  '/backups/targets': typeof AuthBackupsTargetsRouteWithChildren
  '/database-servers/$serverId': typeof AuthDatabaseServersServerIdRoute
  '/database-servers/new': typeof AuthDatabaseServersNewRoute
  '/databases/$databaseId': typeof AuthDatabasesDatabaseIdRoute
  '/databases/new': typeof AuthDatabasesNewRoute
  '/domains/': typeof AuthDomainsIndexRoute
  '/domains/$domainId': typeof AuthDomainsDomainIdRoute
  '/domains/new': typeof AuthDomainsNewRoute
  '/mail/domains': typeof AuthMailDomainsRouteWithChildren
  '/mail/mailboxes': typeof AuthMailMailboxesRoute
  '/mail/queue': typeof AuthMailQueueRoute
  '/plugins/$pluginId': typeof AuthPluginsPluginIdRoute
  '/servers/$serverId': typeof AuthServersServerIdRouteWithChildren
  '/servers/new': typeof AuthServersNewRoute
  '/settings/mcp': typeof AuthSettingsMcpRoute
  '/settings/security': typeof AuthSettingsSecurityRoute
  '/settings/profile': typeof AuthSettingsProfileRoute
  '/settings/general': typeof AuthSettingsGeneralRoute
  '/settings/smtp': typeof AuthSettingsSmtpRoute
  '/settings/notifications': typeof AuthSettingsNotificationsRoute
  '/settings/access': typeof AuthSettingsAccessRoute
  '/settings/storage': typeof AuthSettingsStorageRoute
  '/settings/branding': typeof AuthSettingsBrandingRoute
  '/settings/dns': typeof AuthSettingsDnsRoute
  '/settings/defaults': typeof AuthSettingsDefaultsRoute
  '/settings/security-policy': typeof AuthSettingsSecurityPolicyRoute
  '/sites/$siteId': typeof AuthSitesSiteIdRouteWithChildren
  '/sites/new': typeof AuthSitesNewRoute
  '/wordpress/$installId': typeof AuthWordpressInstallIdRouteWithChildren
  '/plugins': typeof AuthPluginsIndexRoute
  '/sites/$siteId/': typeof AuthSitesSiteIdIndexRoute
  '/sites/$siteId/deployments': typeof AuthSitesSiteIdDeploymentsRoute
  '/sites/$siteId/domains': typeof AuthSitesSiteIdDomainsRoute
  '/sites/$siteId/ssl': typeof AuthSitesSiteIdSslRoute
  '/sites/$siteId/databases': typeof AuthSitesSiteIdDatabasesRoute
  '/sites/$siteId/daemons': typeof AuthSitesSiteIdDaemonsRoute
  '/sites/$siteId/cron': typeof AuthSitesSiteIdCronRoute
  '/sites/$siteId/logs': typeof AuthSitesSiteIdLogsRoute
  '/sites/$siteId/settings': typeof AuthSitesSiteIdSettingsRoute
  '/sites/$siteId/danger': typeof AuthSitesSiteIdDangerRoute
  '/sites/$siteId/backups': typeof AuthSitesSiteIdBackupsRoute
  '/sites/$siteId/dns': typeof AuthSitesSiteIdDnsRoute
  '/sites/$siteId/php': typeof AuthSitesSiteIdPhpRoute
  '/sites/$siteId/files': typeof AuthSitesSiteIdFilesRoute
  '/sites/$siteId/email': typeof AuthSitesSiteIdEmailRoute
  '/sites/$siteId/analytics': typeof AuthSitesSiteIdAnalyticsRoute
  '/files': typeof AuthFilesIndexRoute
  '/files/$siteId': typeof AuthFilesSiteIdRoute
  '/editor/$siteId': typeof AuthEditorSiteIdRoute
  '/tools/phpmyadmin': typeof AuthToolsPhpMyAdminRoute
  '/servers': typeof AuthServersIndexRoute
  '/sites': typeof AuthSitesIndexRoute
  '/wordpress': typeof AuthWordpressIndexRoute
  '/wordpress/$installId/': typeof AuthWordpressInstallIdIndexRoute
  '/wordpress/$installId/plugins': typeof AuthWordpressInstallIdPluginsRoute
  '/wordpress/$installId/themes': typeof AuthWordpressInstallIdThemesRoute
  '/wordpress/$installId/database': typeof AuthWordpressInstallIdDatabaseRoute
  '/wordpress/$installId/security': typeof AuthWordpressInstallIdSecurityRoute
  '/wordpress/$installId/users': typeof AuthWordpressInstallIdUsersRoute
  '/wordpress/$installId/backups': typeof AuthWordpressInstallIdBackupsRoute
  '/wordpress/$installId/settings': typeof AuthWordpressInstallIdSettingsRoute
  '/wordpress/$installId/staging': typeof AuthWordpressInstallIdStagingRoute
  '/wordpress/$installId/danger': typeof AuthWordpressInstallIdDangerRoute
  '/backups/jobs/new': typeof AuthBackupsJobsNewRoute
  '/backups/targets/new': typeof AuthBackupsTargetsNewRoute
  '/mail/domains/$mailDomainId': typeof AuthMailDomainsMailDomainIdRouteWithChildren
  '/mail/domains/new': typeof AuthMailDomainsNewRoute
  '/servers/$serverId/maintenance': typeof AuthServersServerIdMaintenanceRoute
  '/mail/domains/$mailDomainId/diagnostics': typeof AuthMailDomainsMailDomainIdDiagnosticsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/alerts': typeof AuthAlertsRoute
  '/_auth/audit-log': typeof AuthAuditLogRoute
  '/_auth/backups': typeof AuthBackupsRouteWithChildren
  '/_auth/daemons': typeof AuthDaemonsRoute
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/_auth/database-servers': typeof AuthDatabaseServersRouteWithChildren
  '/_auth/databases': typeof AuthDatabasesRouteWithChildren
  '/_auth/domains': typeof AuthDomainsRouteWithChildren
  '/_auth/mail': typeof AuthMailRouteWithChildren
  '/_auth/operators': typeof AuthOperatorsRoute
  '/_auth/plugins': typeof AuthPluginsRouteWithChildren
  '/_auth/scheduled-tasks': typeof AuthScheduledTasksRoute
  '/_auth/servers': typeof AuthServersRouteWithChildren
  '/_auth/settings': typeof AuthSettingsRouteWithChildren
  '/_auth/sites': typeof AuthSitesRouteWithChildren
  '/_auth/templates': typeof AuthTemplatesRoute
  '/_auth/wordpress': typeof AuthWordpressRouteWithChildren
  '/_auth/backups/jobs': typeof AuthBackupsJobsRouteWithChildren
  '/_auth/backups/snapshots': typeof AuthBackupsSnapshotsRoute
  '/_auth/backups/targets': typeof AuthBackupsTargetsRouteWithChildren
  '/_auth/database-servers/$serverId': typeof AuthDatabaseServersServerIdRoute
  '/_auth/database-servers/new': typeof AuthDatabaseServersNewRoute
  '/_auth/databases/$databaseId': typeof AuthDatabasesDatabaseIdRoute
  '/_auth/databases/new': typeof AuthDatabasesNewRoute
  '/_auth/domains/': typeof AuthDomainsIndexRoute
  '/_auth/domains/$domainId': typeof AuthDomainsDomainIdRoute
  '/_auth/domains/new': typeof AuthDomainsNewRoute
  '/_auth/mail/domains': typeof AuthMailDomainsRouteWithChildren
  '/_auth/mail/mailboxes': typeof AuthMailMailboxesRoute
  '/_auth/mail/queue': typeof AuthMailQueueRoute
  '/_auth/plugins/$pluginId': typeof AuthPluginsPluginIdRoute
  '/_auth/servers/$serverId': typeof AuthServersServerIdRouteWithChildren
  '/_auth/servers/new': typeof AuthServersNewRoute
  '/_auth/settings/mcp': typeof AuthSettingsMcpRoute
  '/_auth/settings/security': typeof AuthSettingsSecurityRoute
  '/_auth/settings/profile': typeof AuthSettingsProfileRoute
  '/_auth/settings/general': typeof AuthSettingsGeneralRoute
  '/_auth/settings/smtp': typeof AuthSettingsSmtpRoute
  '/_auth/settings/notifications': typeof AuthSettingsNotificationsRoute
  '/_auth/settings/access': typeof AuthSettingsAccessRoute
  '/_auth/settings/storage': typeof AuthSettingsStorageRoute
  '/_auth/settings/branding': typeof AuthSettingsBrandingRoute
  '/_auth/settings/dns': typeof AuthSettingsDnsRoute
  '/_auth/settings/defaults': typeof AuthSettingsDefaultsRoute
  '/_auth/settings/security-policy': typeof AuthSettingsSecurityPolicyRoute
  '/_auth/sites/$siteId': typeof AuthSitesSiteIdRouteWithChildren
  '/_auth/sites/new': typeof AuthSitesNewRoute
  '/_auth/wordpress/$installId': typeof AuthWordpressInstallIdRouteWithChildren
  '/_auth/sites/$siteId/': typeof AuthSitesSiteIdIndexRoute
  '/_auth/sites/$siteId/deployments': typeof AuthSitesSiteIdDeploymentsRoute
  '/_auth/sites/$siteId/domains': typeof AuthSitesSiteIdDomainsRoute
  '/_auth/sites/$siteId/ssl': typeof AuthSitesSiteIdSslRoute
  '/_auth/sites/$siteId/databases': typeof AuthSitesSiteIdDatabasesRoute
  '/_auth/sites/$siteId/daemons': typeof AuthSitesSiteIdDaemonsRoute
  '/_auth/sites/$siteId/cron': typeof AuthSitesSiteIdCronRoute
  '/_auth/sites/$siteId/logs': typeof AuthSitesSiteIdLogsRoute
  '/_auth/sites/$siteId/settings': typeof AuthSitesSiteIdSettingsRoute
  '/_auth/sites/$siteId/danger': typeof AuthSitesSiteIdDangerRoute
  '/_auth/sites/$siteId/backups': typeof AuthSitesSiteIdBackupsRoute
  '/_auth/sites/$siteId/dns': typeof AuthSitesSiteIdDnsRoute
  '/_auth/sites/$siteId/php': typeof AuthSitesSiteIdPhpRoute
  '/_auth/sites/$siteId/files': typeof AuthSitesSiteIdFilesRoute
  '/_auth/sites/$siteId/email': typeof AuthSitesSiteIdEmailRoute
  '/_auth/sites/$siteId/analytics': typeof AuthSitesSiteIdAnalyticsRoute
  '/_auth/files': typeof AuthFilesRouteWithChildren
  '/_auth/files/': typeof AuthFilesIndexRoute
  '/_auth/files/$siteId': typeof AuthFilesSiteIdRoute
  '/_auth/editor/$siteId': typeof AuthEditorSiteIdRoute
  '/_auth/tools/phpmyadmin': typeof AuthToolsPhpMyAdminRoute
  '/_auth/plugins/': typeof AuthPluginsIndexRoute
  '/_auth/servers/': typeof AuthServersIndexRoute
  '/_auth/sites/': typeof AuthSitesIndexRoute
  '/_auth/wordpress/': typeof AuthWordpressIndexRoute
  '/_auth/wordpress/$installId/': typeof AuthWordpressInstallIdIndexRoute
  '/_auth/wordpress/$installId/plugins': typeof AuthWordpressInstallIdPluginsRoute
  '/_auth/wordpress/$installId/themes': typeof AuthWordpressInstallIdThemesRoute
  '/_auth/wordpress/$installId/database': typeof AuthWordpressInstallIdDatabaseRoute
  '/_auth/wordpress/$installId/security': typeof AuthWordpressInstallIdSecurityRoute
  '/_auth/wordpress/$installId/users': typeof AuthWordpressInstallIdUsersRoute
  '/_auth/wordpress/$installId/backups': typeof AuthWordpressInstallIdBackupsRoute
  '/_auth/wordpress/$installId/settings': typeof AuthWordpressInstallIdSettingsRoute
  '/_auth/wordpress/$installId/staging': typeof AuthWordpressInstallIdStagingRoute
  '/_auth/wordpress/$installId/danger': typeof AuthWordpressInstallIdDangerRoute
  '/_auth/backups/jobs/new': typeof AuthBackupsJobsNewRoute
  '/_auth/backups/targets/new': typeof AuthBackupsTargetsNewRoute
  '/_auth/mail/domains/$mailDomainId': typeof AuthMailDomainsMailDomainIdRouteWithChildren
  '/_auth/mail/domains/new': typeof AuthMailDomainsNewRoute
  '/_auth/servers/$serverId/maintenance': typeof AuthServersServerIdMaintenanceRoute
  '/_auth/mail/domains/$mailDomainId/diagnostics': typeof AuthMailDomainsMailDomainIdDiagnosticsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/alerts'
    | '/audit-log'
    | '/backups'
    | '/daemons'
    | '/dashboard'
    | '/database-servers'
    | '/databases'
    | '/domains'
    | '/mail'
    | '/operators'
    | '/plugins'
    | '/scheduled-tasks'
    | '/servers'
    | '/settings'
    | '/sites'
    | '/templates'
    | '/wordpress'
    | '/backups/jobs'
    | '/backups/snapshots'
    | '/backups/targets'
    | '/database-servers/$serverId'
    | '/database-servers/new'
    | '/databases/$databaseId'
    | '/databases/new'
    | '/domains/$domainId'
    | '/domains/new'
    | '/mail/domains'
    | '/mail/mailboxes'
    | '/mail/queue'
    | '/plugins/$pluginId'
    | '/servers/$serverId'
    | '/servers/new'
    | '/settings/mcp'
    | '/settings/security'
    | '/settings/profile'
    | '/settings/general'
    | '/settings/smtp'
    | '/settings/notifications'
    | '/settings/access'
    | '/settings/storage'
    | '/settings/branding'
    | '/settings/dns'
    | '/settings/defaults'
    | '/settings/security-policy'
    | '/sites/$siteId'
    | '/sites/new'
    | '/wordpress/$installId'
    | '/plugins/'
    | '/sites/$siteId/'
    | '/sites/$siteId/deployments'
    | '/sites/$siteId/domains'
    | '/sites/$siteId/ssl'
    | '/sites/$siteId/databases'
    | '/sites/$siteId/daemons'
    | '/sites/$siteId/cron'
    | '/sites/$siteId/logs'
    | '/sites/$siteId/settings'
    | '/sites/$siteId/danger'
    | '/sites/$siteId/backups'
    | '/sites/$siteId/dns'
    | '/sites/$siteId/php'
    | '/sites/$siteId/files'
    | '/sites/$siteId/email'
    | '/sites/$siteId/analytics'
    | '/files'
    | '/files/'
    | '/files/$siteId'
    | '/editor/$siteId'
    | '/tools/phpmyadmin'
    | '/servers/'
    | '/sites/'
    | '/wordpress/'
    | '/wordpress/$installId/'
    | '/wordpress/$installId/plugins'
    | '/wordpress/$installId/themes'
    | '/wordpress/$installId/database'
    | '/wordpress/$installId/security'
    | '/wordpress/$installId/users'
    | '/wordpress/$installId/backups'
    | '/wordpress/$installId/settings'
    | '/wordpress/$installId/staging'
    | '/wordpress/$installId/danger'
    | '/backups/jobs/new'
    | '/backups/targets/new'
    | '/mail/domains/$mailDomainId'
    | '/mail/domains/new'
    | '/servers/$serverId/maintenance'
    | '/mail/domains/$mailDomainId/diagnostics'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/alerts'
    | '/audit-log'
    | '/backups'
    | '/daemons'
    | '/dashboard'
    | '/database-servers'
    | '/databases'
    | '/domains'
    | '/mail'
    | '/operators'
    | '/scheduled-tasks'
    | '/settings'
    | '/templates'
    | '/backups/jobs'
    | '/backups/snapshots'
    | '/backups/targets'
    | '/database-servers/$serverId'
    | '/database-servers/new'
    | '/databases/$databaseId'
    | '/databases/new'
    | '/domains/$domainId'
    | '/domains/new'
    | '/mail/domains'
    | '/mail/mailboxes'
    | '/mail/queue'
    | '/plugins/$pluginId'
    | '/servers/$serverId'
    | '/servers/new'
    | '/settings/mcp'
    | '/settings/security'
    | '/settings/profile'
    | '/settings/general'
    | '/settings/smtp'
    | '/settings/notifications'
    | '/settings/access'
    | '/settings/storage'
    | '/settings/branding'
    | '/settings/dns'
    | '/settings/defaults'
    | '/settings/security-policy'
    | '/sites/$siteId'
    | '/sites/new'
    | '/wordpress/$installId'
    | '/plugins'
    | '/sites/$siteId/'
    | '/sites/$siteId/deployments'
    | '/sites/$siteId/domains'
    | '/sites/$siteId/ssl'
    | '/sites/$siteId/databases'
    | '/sites/$siteId/daemons'
    | '/sites/$siteId/cron'
    | '/sites/$siteId/logs'
    | '/sites/$siteId/settings'
    | '/sites/$siteId/danger'
    | '/sites/$siteId/backups'
    | '/sites/$siteId/dns'
    | '/sites/$siteId/php'
    | '/sites/$siteId/files'
    | '/sites/$siteId/email'
    | '/sites/$siteId/analytics'
    | '/files'
    | '/files/$siteId'
    | '/editor/$siteId'
    | '/tools/phpmyadmin'
    | '/servers'
    | '/sites'
    | '/wordpress'
    | '/wordpress/$installId/'
    | '/wordpress/$installId/plugins'
    | '/wordpress/$installId/themes'
    | '/wordpress/$installId/database'
    | '/wordpress/$installId/security'
    | '/wordpress/$installId/users'
    | '/wordpress/$installId/backups'
    | '/wordpress/$installId/settings'
    | '/wordpress/$installId/staging'
    | '/wordpress/$installId/danger'
    | '/backups/jobs/new'
    | '/backups/targets/new'
    | '/mail/domains/$mailDomainId'
    | '/mail/domains/new'
    | '/servers/$serverId/maintenance'
    | '/mail/domains/$mailDomainId/diagnostics'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/login'
    | '/_auth/alerts'
    | '/_auth/audit-log'
    | '/_auth/backups'
    | '/_auth/daemons'
    | '/_auth/dashboard'
    | '/_auth/database-servers'
    | '/_auth/databases'
    | '/_auth/domains'
    | '/_auth/mail'
    | '/_auth/operators'
    | '/_auth/plugins'
    | '/_auth/scheduled-tasks'
    | '/_auth/servers'
    | '/_auth/settings'
    | '/_auth/sites'
    | '/_auth/templates'
    | '/_auth/wordpress'
    | '/_auth/backups/jobs'
    | '/_auth/backups/snapshots'
    | '/_auth/backups/targets'
    | '/_auth/database-servers/$serverId'
    | '/_auth/database-servers/new'
    | '/_auth/databases/$databaseId'
    | '/_auth/databases/new'
    | '/_auth/domains/$domainId'
    | '/_auth/domains/new'
    | '/_auth/mail/domains'
    | '/_auth/mail/mailboxes'
    | '/_auth/mail/queue'
    | '/_auth/plugins/$pluginId'
    | '/_auth/servers/$serverId'
    | '/_auth/servers/new'
    | '/_auth/settings/mcp'
    | '/_auth/settings/security'
    | '/_auth/settings/profile'
    | '/_auth/settings/general'
    | '/_auth/settings/smtp'
    | '/_auth/settings/notifications'
    | '/_auth/settings/access'
    | '/_auth/settings/storage'
    | '/_auth/settings/branding'
    | '/_auth/settings/dns'
    | '/_auth/settings/defaults'
    | '/_auth/settings/security-policy'
    | '/_auth/sites/$siteId'
    | '/_auth/sites/new'
    | '/_auth/wordpress/$installId'
    | '/_auth/sites/$siteId/'
    | '/_auth/sites/$siteId/deployments'
    | '/_auth/sites/$siteId/domains'
    | '/_auth/sites/$siteId/ssl'
    | '/_auth/sites/$siteId/databases'
    | '/_auth/sites/$siteId/daemons'
    | '/_auth/sites/$siteId/cron'
    | '/_auth/sites/$siteId/logs'
    | '/_auth/sites/$siteId/settings'
    | '/_auth/sites/$siteId/danger'
    | '/_auth/sites/$siteId/backups'
    | '/_auth/sites/$siteId/dns'
    | '/_auth/sites/$siteId/php'
    | '/_auth/sites/$siteId/files'
    | '/_auth/sites/$siteId/email'
    | '/_auth/sites/$siteId/analytics'
    | '/_auth/files'
    | '/_auth/files/'
    | '/_auth/files/$siteId'
    | '/_auth/editor/$siteId'
    | '/_auth/tools/phpmyadmin'
    | '/_auth/plugins/'
    | '/_auth/servers/'
    | '/_auth/sites/'
    | '/_auth/wordpress/'
    | '/_auth/wordpress/$installId/'
    | '/_auth/wordpress/$installId/plugins'
    | '/_auth/wordpress/$installId/themes'
    | '/_auth/wordpress/$installId/database'
    | '/_auth/wordpress/$installId/security'
    | '/_auth/wordpress/$installId/users'
    | '/_auth/wordpress/$installId/backups'
    | '/_auth/wordpress/$installId/settings'
    | '/_auth/wordpress/$installId/staging'
    | '/_auth/wordpress/$installId/danger'
    | '/_auth/backups/jobs/new'
    | '/_auth/backups/targets/new'
    | '/_auth/mail/domains/$mailDomainId'
    | '/_auth/mail/domains/new'
    | '/_auth/servers/$serverId/maintenance'
    | '/_auth/mail/domains/$mailDomainId/diagnostics'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/wordpress': {
      id: '/_auth/wordpress'
      path: '/wordpress'
      fullPath: '/wordpress'
      preLoaderRoute: typeof AuthWordpressRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/templates': {
      id: '/_auth/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AuthTemplatesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sites': {
      id: '/_auth/sites'
      path: '/sites'
      fullPath: '/sites'
      preLoaderRoute: typeof AuthSitesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/settings': {
      id: '/_auth/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthSettingsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/servers': {
      id: '/_auth/servers'
      path: '/servers'
      fullPath: '/servers'
      preLoaderRoute: typeof AuthServersRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/scheduled-tasks': {
      id: '/_auth/scheduled-tasks'
      path: '/scheduled-tasks'
      fullPath: '/scheduled-tasks'
      preLoaderRoute: typeof AuthScheduledTasksRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/plugins': {
      id: '/_auth/plugins'
      path: '/plugins'
      fullPath: '/plugins'
      preLoaderRoute: typeof AuthPluginsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/operators': {
      id: '/_auth/operators'
      path: '/operators'
      fullPath: '/operators'
      preLoaderRoute: typeof AuthOperatorsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/mail': {
      id: '/_auth/mail'
      path: '/mail'
      fullPath: '/mail'
      preLoaderRoute: typeof AuthMailRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/domains': {
      id: '/_auth/domains'
      path: '/domains'
      fullPath: '/domains'
      preLoaderRoute: typeof AuthDomainsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/databases': {
      id: '/_auth/databases'
      path: '/databases'
      fullPath: '/databases'
      preLoaderRoute: typeof AuthDatabasesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/database-servers': {
      id: '/_auth/database-servers'
      path: '/database-servers'
      fullPath: '/database-servers'
      preLoaderRoute: typeof AuthDatabaseServersRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/daemons': {
      id: '/_auth/daemons'
      path: '/daemons'
      fullPath: '/daemons'
      preLoaderRoute: typeof AuthDaemonsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/backups': {
      id: '/_auth/backups'
      path: '/backups'
      fullPath: '/backups'
      preLoaderRoute: typeof AuthBackupsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/audit-log': {
      id: '/_auth/audit-log'
      path: '/audit-log'
      fullPath: '/audit-log'
      preLoaderRoute: typeof AuthAuditLogRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/alerts': {
      id: '/_auth/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AuthAlertsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/wordpress/': {
      id: '/_auth/wordpress/'
      path: '/'
      fullPath: '/wordpress/'
      preLoaderRoute: typeof AuthWordpressIndexRouteImport
      parentRoute: typeof AuthWordpressRoute
    }
    '/_auth/sites/': {
      id: '/_auth/sites/'
      path: '/'
      fullPath: '/sites/'
      preLoaderRoute: typeof AuthSitesIndexRouteImport
      parentRoute: typeof AuthSitesRoute
    }
    '/_auth/servers/': {
      id: '/_auth/servers/'
      path: '/'
      fullPath: '/servers/'
      preLoaderRoute: typeof AuthServersIndexRouteImport
      parentRoute: typeof AuthServersRoute
    }
    '/_auth/plugins/': {
      id: '/_auth/plugins/'
      path: '/'
      fullPath: '/plugins/'
      preLoaderRoute: typeof AuthPluginsIndexRouteImport
      parentRoute: typeof AuthPluginsRoute
    }
    '/_auth/wordpress/$installId': {
      id: '/_auth/wordpress/$installId'
      path: '/$installId'
      fullPath: '/wordpress/$installId'
      preLoaderRoute: typeof AuthWordpressInstallIdRouteImport
      parentRoute: typeof AuthWordpressRoute
    }
    '/_auth/wordpress/$installId/': {
      id: '/_auth/wordpress/$installId/'
      path: '/'
      fullPath: '/wordpress/$installId/'
      preLoaderRoute: typeof AuthWordpressInstallIdIndexRouteImport
      parentRoute: typeof AuthWordpressInstallIdRoute
    }
    '/_auth/wordpress/$installId/plugins': {
      id: '/_auth/wordpress/$installId/plugins'
      path: '/plugins'
      fullPath: '/wordpress/$installId/plugins'
      preLoaderRoute: typeof AuthWordpressInstallIdPluginsRouteImport
      parentRoute: typeof AuthWordpressInstallIdRoute
    }
    '/_auth/wordpress/$installId/themes': {
      id: '/_auth/wordpress/$installId/themes'
      path: '/themes'
      fullPath: '/wordpress/$installId/themes'
      preLoaderRoute: typeof AuthWordpressInstallIdThemesRouteImport
      parentRoute: typeof AuthWordpressInstallIdRoute
    }
    '/_auth/wordpress/$installId/database': {
      id: '/_auth/wordpress/$installId/database'
      path: '/database'
      fullPath: '/wordpress/$installId/database'
      preLoaderRoute: typeof AuthWordpressInstallIdDatabaseRouteImport
      parentRoute: typeof AuthWordpressInstallIdRoute
    }
    '/_auth/wordpress/$installId/security': {
      id: '/_auth/wordpress/$installId/security'
      path: '/security'
      fullPath: '/wordpress/$installId/security'
      preLoaderRoute: typeof AuthWordpressInstallIdSecurityRouteImport
      parentRoute: typeof AuthWordpressInstallIdRoute
    }
    '/_auth/wordpress/$installId/users': {
      id: '/_auth/wordpress/$installId/users'
      path: '/users'
      fullPath: '/wordpress/$installId/users'
      preLoaderRoute: typeof AuthWordpressInstallIdUsersRouteImport
      parentRoute: typeof AuthWordpressInstallIdRoute
    }
    '/_auth/wordpress/$installId/backups': {
      id: '/_auth/wordpress/$installId/backups'
      path: '/backups'
      fullPath: '/wordpress/$installId/backups'
      preLoaderRoute: typeof AuthWordpressInstallIdBackupsRouteImport
      parentRoute: typeof AuthWordpressInstallIdRoute
    }
    '/_auth/wordpress/$installId/settings': {
      id: '/_auth/wordpress/$installId/settings'
      path: '/settings'
      fullPath: '/wordpress/$installId/settings'
      preLoaderRoute: typeof AuthWordpressInstallIdSettingsRouteImport
      parentRoute: typeof AuthWordpressInstallIdRoute
    }
    '/_auth/wordpress/$installId/staging': {
      id: '/_auth/wordpress/$installId/staging'
      path: '/staging'
      fullPath: '/wordpress/$installId/staging'
      preLoaderRoute: typeof AuthWordpressInstallIdStagingRouteImport
      parentRoute: typeof AuthWordpressInstallIdRoute
    }
    '/_auth/wordpress/$installId/danger': {
      id: '/_auth/wordpress/$installId/danger'
      path: '/danger'
      fullPath: '/wordpress/$installId/danger'
      preLoaderRoute: typeof AuthWordpressInstallIdDangerRouteImport
      parentRoute: typeof AuthWordpressInstallIdRoute
    }
    '/_auth/sites/new': {
      id: '/_auth/sites/new'
      path: '/new'
      fullPath: '/sites/new'
      preLoaderRoute: typeof AuthSitesNewRouteImport
      parentRoute: typeof AuthSitesRoute
    }
    '/_auth/sites/$siteId': {
      id: '/_auth/sites/$siteId'
      path: '/$siteId'
      fullPath: '/sites/$siteId'
      preLoaderRoute: typeof AuthSitesSiteIdRouteImport
      parentRoute: typeof AuthSitesRoute
    }
    '/_auth/sites/$siteId/': {
      id: '/_auth/sites/$siteId/'
      path: '/'
      fullPath: '/sites/$siteId/'
      preLoaderRoute: typeof AuthSitesSiteIdIndexRouteImport
      parentRoute: typeof AuthSitesSiteIdRoute
    }
    '/_auth/sites/$siteId/deployments': {
      id: '/_auth/sites/$siteId/deployments'
      path: '/deployments'
      fullPath: '/sites/$siteId/deployments'
      preLoaderRoute: typeof AuthSitesSiteIdDeploymentsRouteImport
      parentRoute: typeof AuthSitesSiteIdRoute
    }
    '/_auth/sites/$siteId/domains': {
      id: '/_auth/sites/$siteId/domains'
      path: '/domains'
      fullPath: '/sites/$siteId/domains'
      preLoaderRoute: typeof AuthSitesSiteIdDomainsRouteImport
      parentRoute: typeof AuthSitesSiteIdRoute
    }
    '/_auth/sites/$siteId/ssl': {
      id: '/_auth/sites/$siteId/ssl'
      path: '/ssl'
      fullPath: '/sites/$siteId/ssl'
      preLoaderRoute: typeof AuthSitesSiteIdSslRouteImport
      parentRoute: typeof AuthSitesSiteIdRoute
    }
    '/_auth/sites/$siteId/databases': {
      id: '/_auth/sites/$siteId/databases'
      path: '/databases'
      fullPath: '/sites/$siteId/databases'
      preLoaderRoute: typeof AuthSitesSiteIdDatabasesRouteImport
      parentRoute: typeof AuthSitesSiteIdRoute
    }
    '/_auth/sites/$siteId/daemons': {
      id: '/_auth/sites/$siteId/daemons'
      path: '/daemons'
      fullPath: '/sites/$siteId/daemons'
      preLoaderRoute: typeof AuthSitesSiteIdDaemonsRouteImport
      parentRoute: typeof AuthSitesSiteIdRoute
    }
    '/_auth/sites/$siteId/cron': {
      id: '/_auth/sites/$siteId/cron'
      path: '/cron'
      fullPath: '/sites/$siteId/cron'
      preLoaderRoute: typeof AuthSitesSiteIdCronRouteImport
      parentRoute: typeof AuthSitesSiteIdRoute
    }
    '/_auth/sites/$siteId/logs': {
      id: '/_auth/sites/$siteId/logs'
      path: '/logs'
      fullPath: '/sites/$siteId/logs'
      preLoaderRoute: typeof AuthSitesSiteIdLogsRouteImport
      parentRoute: typeof AuthSitesSiteIdRoute
    }
    '/_auth/sites/$siteId/settings': {
      id: '/_auth/sites/$siteId/settings'
      path: '/settings'
      fullPath: '/sites/$siteId/settings'
      preLoaderRoute: typeof AuthSitesSiteIdSettingsRouteImport
      parentRoute: typeof AuthSitesSiteIdRoute
    }
    '/_auth/sites/$siteId/danger': {
      id: '/_auth/sites/$siteId/danger'
      path: '/danger'
      fullPath: '/sites/$siteId/danger'
      preLoaderRoute: typeof AuthSitesSiteIdDangerRouteImport
      parentRoute: typeof AuthSitesSiteIdRoute
    }
    '/_auth/sites/$siteId/backups': {
      id: '/_auth/sites/$siteId/backups'
      path: '/backups'
      fullPath: '/sites/$siteId/backups'
      preLoaderRoute: typeof AuthSitesSiteIdBackupsRouteImport
      parentRoute: typeof AuthSitesSiteIdRoute
    }
    '/_auth/sites/$siteId/dns': {
      id: '/_auth/sites/$siteId/dns'
      path: '/dns'
      fullPath: '/sites/$siteId/dns'
      preLoaderRoute: typeof AuthSitesSiteIdDnsRouteImport
      parentRoute: typeof AuthSitesSiteIdRoute
    }
    '/_auth/sites/$siteId/php': {
      id: '/_auth/sites/$siteId/php'
      path: '/php'
      fullPath: '/sites/$siteId/php'
      preLoaderRoute: typeof AuthSitesSiteIdPhpRouteImport
      parentRoute: typeof AuthSitesSiteIdRoute
    }
    '/_auth/sites/$siteId/files': {
      id: '/_auth/sites/$siteId/files'
      path: '/files'
      fullPath: '/sites/$siteId/files'
      preLoaderRoute: typeof AuthSitesSiteIdFilesRouteImport
      parentRoute: typeof AuthSitesSiteIdRoute
    }
    '/_auth/sites/$siteId/email': {
      id: '/_auth/sites/$siteId/email'
      path: '/email'
      fullPath: '/sites/$siteId/email'
      preLoaderRoute: typeof AuthSitesSiteIdEmailRouteImport
      parentRoute: typeof AuthSitesSiteIdRoute
    }
    '/_auth/sites/$siteId/analytics': {
      id: '/_auth/sites/$siteId/analytics'
      path: '/analytics'
      fullPath: '/sites/$siteId/analytics'
      preLoaderRoute: typeof AuthSitesSiteIdAnalyticsRouteImport
      parentRoute: typeof AuthSitesSiteIdRoute
    }
    '/_auth/files': {
      id: '/_auth/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof AuthFilesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/files/': {
      id: '/_auth/files/'
      path: '/'
      fullPath: '/files/'
      preLoaderRoute: typeof AuthFilesIndexRouteImport
      parentRoute: typeof AuthFilesRoute
    }
    '/_auth/files/$siteId': {
      id: '/_auth/files/$siteId'
      path: '/$siteId'
      fullPath: '/files/$siteId'
      preLoaderRoute: typeof AuthFilesSiteIdRouteImport
      parentRoute: typeof AuthFilesRoute
    }
    '/_auth/editor/$siteId': {
      id: '/_auth/editor/$siteId'
      path: '/editor/$siteId'
      fullPath: '/editor/$siteId'
      preLoaderRoute: typeof AuthEditorSiteIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/tools/phpmyadmin': {
      id: '/_auth/tools/phpmyadmin'
      path: '/tools/phpmyadmin'
      fullPath: '/tools/phpmyadmin'
      preLoaderRoute: typeof AuthToolsPhpMyAdminRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/settings/security': {
      id: '/_auth/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof AuthSettingsSecurityRouteImport
      parentRoute: typeof AuthSettingsRoute
    }
    '/_auth/settings/mcp': {
      id: '/_auth/settings/mcp'
      path: '/mcp'
      fullPath: '/settings/mcp'
      preLoaderRoute: typeof AuthSettingsMcpRouteImport
      parentRoute: typeof AuthSettingsRoute
    }
    '/_auth/settings/profile': {
      id: '/_auth/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AuthSettingsProfileRouteImport
      parentRoute: typeof AuthSettingsRoute
    }
    '/_auth/settings/general': {
      id: '/_auth/settings/general'
      path: '/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof AuthSettingsGeneralRouteImport
      parentRoute: typeof AuthSettingsRoute
    }
    '/_auth/settings/smtp': {
      id: '/_auth/settings/smtp'
      path: '/smtp'
      fullPath: '/settings/smtp'
      preLoaderRoute: typeof AuthSettingsSmtpRouteImport
      parentRoute: typeof AuthSettingsRoute
    }
    '/_auth/settings/notifications': {
      id: '/_auth/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthSettingsNotificationsRouteImport
      parentRoute: typeof AuthSettingsRoute
    }
    '/_auth/settings/access': {
      id: '/_auth/settings/access'
      path: '/access'
      fullPath: '/settings/access'
      preLoaderRoute: typeof AuthSettingsAccessRouteImport
      parentRoute: typeof AuthSettingsRoute
    }
    '/_auth/settings/storage': {
      id: '/_auth/settings/storage'
      path: '/storage'
      fullPath: '/settings/storage'
      preLoaderRoute: typeof AuthSettingsStorageRouteImport
      parentRoute: typeof AuthSettingsRoute
    }
    '/_auth/settings/branding': {
      id: '/_auth/settings/branding'
      path: '/branding'
      fullPath: '/settings/branding'
      preLoaderRoute: typeof AuthSettingsBrandingRouteImport
      parentRoute: typeof AuthSettingsRoute
    }
    '/_auth/settings/dns': {
      id: '/_auth/settings/dns'
      path: '/dns'
      fullPath: '/settings/dns'
      preLoaderRoute: typeof AuthSettingsDnsRouteImport
      parentRoute: typeof AuthSettingsRoute
    }
    '/_auth/settings/defaults': {
      id: '/_auth/settings/defaults'
      path: '/defaults'
      fullPath: '/settings/defaults'
      preLoaderRoute: typeof AuthSettingsDefaultsRouteImport
      parentRoute: typeof AuthSettingsRoute
    }
    '/_auth/settings/security-policy': {
      id: '/_auth/settings/security-policy'
      path: '/security-policy'
      fullPath: '/settings/security-policy'
      preLoaderRoute: typeof AuthSettingsSecurityPolicyRouteImport
      parentRoute: typeof AuthSettingsRoute
    }
    '/_auth/servers/new': {
      id: '/_auth/servers/new'
      path: '/new'
      fullPath: '/servers/new'
      preLoaderRoute: typeof AuthServersNewRouteImport
      parentRoute: typeof AuthServersRoute
    }
    '/_auth/servers/$serverId': {
      id: '/_auth/servers/$serverId'
      path: '/$serverId'
      fullPath: '/servers/$serverId'
      preLoaderRoute: typeof AuthServersServerIdRouteImport
      parentRoute: typeof AuthServersRoute
    }
    '/_auth/plugins/$pluginId': {
      id: '/_auth/plugins/$pluginId'
      path: '/$pluginId'
      fullPath: '/plugins/$pluginId'
      preLoaderRoute: typeof AuthPluginsPluginIdRouteImport
      parentRoute: typeof AuthPluginsRoute
    }
    '/_auth/mail/queue': {
      id: '/_auth/mail/queue'
      path: '/queue'
      fullPath: '/mail/queue'
      preLoaderRoute: typeof AuthMailQueueRouteImport
      parentRoute: typeof AuthMailRoute
    }
    '/_auth/mail/mailboxes': {
      id: '/_auth/mail/mailboxes'
      path: '/mailboxes'
      fullPath: '/mail/mailboxes'
      preLoaderRoute: typeof AuthMailMailboxesRouteImport
      parentRoute: typeof AuthMailRoute
    }
    '/_auth/mail/domains': {
      id: '/_auth/mail/domains'
      path: '/domains'
      fullPath: '/mail/domains'
      preLoaderRoute: typeof AuthMailDomainsRouteImport
      parentRoute: typeof AuthMailRoute
    }
    '/_auth/domains/': {
      id: '/_auth/domains/'
      path: '/'
      fullPath: '/domains/'
      preLoaderRoute: typeof AuthDomainsIndexRouteImport
      parentRoute: typeof AuthDomainsRoute
    }
    '/_auth/domains/new': {
      id: '/_auth/domains/new'
      path: '/new'
      fullPath: '/domains/new'
      preLoaderRoute: typeof AuthDomainsNewRouteImport
      parentRoute: typeof AuthDomainsRoute
    }
    '/_auth/domains/$domainId': {
      id: '/_auth/domains/$domainId'
      path: '/$domainId'
      fullPath: '/domains/$domainId'
      preLoaderRoute: typeof AuthDomainsDomainIdRouteImport
      parentRoute: typeof AuthDomainsRoute
    }
    '/_auth/databases/new': {
      id: '/_auth/databases/new'
      path: '/new'
      fullPath: '/databases/new'
      preLoaderRoute: typeof AuthDatabasesNewRouteImport
      parentRoute: typeof AuthDatabasesRoute
    }
    '/_auth/databases/$databaseId': {
      id: '/_auth/databases/$databaseId'
      path: '/$databaseId'
      fullPath: '/databases/$databaseId'
      preLoaderRoute: typeof AuthDatabasesDatabaseIdRouteImport
      parentRoute: typeof AuthDatabasesRoute
    }
    '/_auth/database-servers/new': {
      id: '/_auth/database-servers/new'
      path: '/new'
      fullPath: '/database-servers/new'
      preLoaderRoute: typeof AuthDatabaseServersNewRouteImport
      parentRoute: typeof AuthDatabaseServersRoute
    }
    '/_auth/database-servers/$serverId': {
      id: '/_auth/database-servers/$serverId'
      path: '/$serverId'
      fullPath: '/database-servers/$serverId'
      preLoaderRoute: typeof AuthDatabaseServersServerIdRouteImport
      parentRoute: typeof AuthDatabaseServersRoute
    }
    '/_auth/backups/targets': {
      id: '/_auth/backups/targets'
      path: '/targets'
      fullPath: '/backups/targets'
      preLoaderRoute: typeof AuthBackupsTargetsRouteImport
      parentRoute: typeof AuthBackupsRoute
    }
    '/_auth/backups/snapshots': {
      id: '/_auth/backups/snapshots'
      path: '/snapshots'
      fullPath: '/backups/snapshots'
      preLoaderRoute: typeof AuthBackupsSnapshotsRouteImport
      parentRoute: typeof AuthBackupsRoute
    }
    '/_auth/backups/jobs': {
      id: '/_auth/backups/jobs'
      path: '/jobs'
      fullPath: '/backups/jobs'
      preLoaderRoute: typeof AuthBackupsJobsRouteImport
      parentRoute: typeof AuthBackupsRoute
    }
    '/_auth/servers/$serverId/maintenance': {
      id: '/_auth/servers/$serverId/maintenance'
      path: '/maintenance'
      fullPath: '/servers/$serverId/maintenance'
      preLoaderRoute: typeof AuthServersServerIdMaintenanceRouteImport
      parentRoute: typeof AuthServersServerIdRoute
    }
    '/_auth/mail/domains/new': {
      id: '/_auth/mail/domains/new'
      path: '/new'
      fullPath: '/mail/domains/new'
      preLoaderRoute: typeof AuthMailDomainsNewRouteImport
      parentRoute: typeof AuthMailDomainsRoute
    }
    '/_auth/mail/domains/$mailDomainId': {
      id: '/_auth/mail/domains/$mailDomainId'
      path: '/$mailDomainId'
      fullPath: '/mail/domains/$mailDomainId'
      preLoaderRoute: typeof AuthMailDomainsMailDomainIdRouteImport
      parentRoute: typeof AuthMailDomainsRoute
    }
    '/_auth/backups/targets/new': {
      id: '/_auth/backups/targets/new'
      path: '/new'
      fullPath: '/backups/targets/new'
      preLoaderRoute: typeof AuthBackupsTargetsNewRouteImport
      parentRoute: typeof AuthBackupsTargetsRoute
    }
    '/_auth/backups/jobs/new': {
      id: '/_auth/backups/jobs/new'
      path: '/new'
      fullPath: '/backups/jobs/new'
      preLoaderRoute: typeof AuthBackupsJobsNewRouteImport
      parentRoute: typeof AuthBackupsJobsRoute
    }
    '/_auth/mail/domains/$mailDomainId/diagnostics': {
      id: '/_auth/mail/domains/$mailDomainId/diagnostics'
      path: '/diagnostics'
      fullPath: '/mail/domains/$mailDomainId/diagnostics'
      preLoaderRoute: typeof AuthMailDomainsMailDomainIdDiagnosticsRouteImport
      parentRoute: typeof AuthMailDomainsMailDomainIdRoute
    }
  }
}

interface AuthBackupsJobsRouteChildren {
  AuthBackupsJobsNewRoute: typeof AuthBackupsJobsNewRoute
}

const AuthBackupsJobsRouteChildren: AuthBackupsJobsRouteChildren = {
  AuthBackupsJobsNewRoute: AuthBackupsJobsNewRoute,
}

const AuthBackupsJobsRouteWithChildren = AuthBackupsJobsRoute._addFileChildren(
  AuthBackupsJobsRouteChildren,
)

interface AuthBackupsTargetsRouteChildren {
  AuthBackupsTargetsNewRoute: typeof AuthBackupsTargetsNewRoute
}

const AuthBackupsTargetsRouteChildren: AuthBackupsTargetsRouteChildren = {
  AuthBackupsTargetsNewRoute: AuthBackupsTargetsNewRoute,
}

const AuthBackupsTargetsRouteWithChildren =
  AuthBackupsTargetsRoute._addFileChildren(AuthBackupsTargetsRouteChildren)

interface AuthBackupsRouteChildren {
  AuthBackupsJobsRoute: typeof AuthBackupsJobsRouteWithChildren
  AuthBackupsSnapshotsRoute: typeof AuthBackupsSnapshotsRoute
  AuthBackupsTargetsRoute: typeof AuthBackupsTargetsRouteWithChildren
}

const AuthBackupsRouteChildren: AuthBackupsRouteChildren = {
  AuthBackupsJobsRoute: AuthBackupsJobsRouteWithChildren,
  AuthBackupsSnapshotsRoute: AuthBackupsSnapshotsRoute,
  AuthBackupsTargetsRoute: AuthBackupsTargetsRouteWithChildren,
}

const AuthBackupsRouteWithChildren = AuthBackupsRoute._addFileChildren(
  AuthBackupsRouteChildren,
)

interface AuthDatabaseServersRouteChildren {
  AuthDatabaseServersServerIdRoute: typeof AuthDatabaseServersServerIdRoute
  AuthDatabaseServersNewRoute: typeof AuthDatabaseServersNewRoute
}

const AuthDatabaseServersRouteChildren: AuthDatabaseServersRouteChildren = {
  AuthDatabaseServersServerIdRoute: AuthDatabaseServersServerIdRoute,
  AuthDatabaseServersNewRoute: AuthDatabaseServersNewRoute,
}

const AuthDatabaseServersRouteWithChildren =
  AuthDatabaseServersRoute._addFileChildren(AuthDatabaseServersRouteChildren)

interface AuthDatabasesRouteChildren {
  AuthDatabasesDatabaseIdRoute: typeof AuthDatabasesDatabaseIdRoute
  AuthDatabasesNewRoute: typeof AuthDatabasesNewRoute
}

const AuthDatabasesRouteChildren: AuthDatabasesRouteChildren = {
  AuthDatabasesDatabaseIdRoute: AuthDatabasesDatabaseIdRoute,
  AuthDatabasesNewRoute: AuthDatabasesNewRoute,
}

const AuthDatabasesRouteWithChildren = AuthDatabasesRoute._addFileChildren(
  AuthDatabasesRouteChildren,
)

interface AuthDomainsRouteChildren {
  AuthDomainsIndexRoute: typeof AuthDomainsIndexRoute
  AuthDomainsDomainIdRoute: typeof AuthDomainsDomainIdRoute
  AuthDomainsNewRoute: typeof AuthDomainsNewRoute
}

const AuthDomainsRouteChildren: AuthDomainsRouteChildren = {
  AuthDomainsIndexRoute: AuthDomainsIndexRoute,
  AuthDomainsDomainIdRoute: AuthDomainsDomainIdRoute,
  AuthDomainsNewRoute: AuthDomainsNewRoute,
}

const AuthDomainsRouteWithChildren = AuthDomainsRoute._addFileChildren(
  AuthDomainsRouteChildren,
)

interface AuthMailDomainsMailDomainIdRouteChildren {
  AuthMailDomainsMailDomainIdDiagnosticsRoute: typeof AuthMailDomainsMailDomainIdDiagnosticsRoute
}

const AuthMailDomainsMailDomainIdRouteChildren: AuthMailDomainsMailDomainIdRouteChildren =
  {
    AuthMailDomainsMailDomainIdDiagnosticsRoute:
      AuthMailDomainsMailDomainIdDiagnosticsRoute,
  }

const AuthMailDomainsMailDomainIdRouteWithChildren =
  AuthMailDomainsMailDomainIdRoute._addFileChildren(
    AuthMailDomainsMailDomainIdRouteChildren,
  )

interface AuthMailDomainsRouteChildren {
  AuthMailDomainsMailDomainIdRoute: typeof AuthMailDomainsMailDomainIdRouteWithChildren
  AuthMailDomainsNewRoute: typeof AuthMailDomainsNewRoute
}

const AuthMailDomainsRouteChildren: AuthMailDomainsRouteChildren = {
  AuthMailDomainsMailDomainIdRoute:
    AuthMailDomainsMailDomainIdRouteWithChildren,
  AuthMailDomainsNewRoute: AuthMailDomainsNewRoute,
}

const AuthMailDomainsRouteWithChildren = AuthMailDomainsRoute._addFileChildren(
  AuthMailDomainsRouteChildren,
)

interface AuthMailRouteChildren {
  AuthMailDomainsRoute: typeof AuthMailDomainsRouteWithChildren
  AuthMailMailboxesRoute: typeof AuthMailMailboxesRoute
  AuthMailQueueRoute: typeof AuthMailQueueRoute
}

const AuthMailRouteChildren: AuthMailRouteChildren = {
  AuthMailDomainsRoute: AuthMailDomainsRouteWithChildren,
  AuthMailMailboxesRoute: AuthMailMailboxesRoute,
  AuthMailQueueRoute: AuthMailQueueRoute,
}

const AuthMailRouteWithChildren = AuthMailRoute._addFileChildren(
  AuthMailRouteChildren,
)

interface AuthPluginsRouteChildren {
  AuthPluginsPluginIdRoute: typeof AuthPluginsPluginIdRoute
  AuthPluginsIndexRoute: typeof AuthPluginsIndexRoute
}

const AuthPluginsRouteChildren: AuthPluginsRouteChildren = {
  AuthPluginsPluginIdRoute: AuthPluginsPluginIdRoute,
  AuthPluginsIndexRoute: AuthPluginsIndexRoute,
}

const AuthPluginsRouteWithChildren = AuthPluginsRoute._addFileChildren(
  AuthPluginsRouteChildren,
)

interface AuthServersServerIdRouteChildren {
  AuthServersServerIdMaintenanceRoute: typeof AuthServersServerIdMaintenanceRoute
}

const AuthServersServerIdRouteChildren: AuthServersServerIdRouteChildren = {
  AuthServersServerIdMaintenanceRoute: AuthServersServerIdMaintenanceRoute,
}

const AuthServersServerIdRouteWithChildren =
  AuthServersServerIdRoute._addFileChildren(AuthServersServerIdRouteChildren)

interface AuthServersRouteChildren {
  AuthServersServerIdRoute: typeof AuthServersServerIdRouteWithChildren
  AuthServersNewRoute: typeof AuthServersNewRoute
  AuthServersIndexRoute: typeof AuthServersIndexRoute
}

const AuthServersRouteChildren: AuthServersRouteChildren = {
  AuthServersServerIdRoute: AuthServersServerIdRouteWithChildren,
  AuthServersNewRoute: AuthServersNewRoute,
  AuthServersIndexRoute: AuthServersIndexRoute,
}

const AuthServersRouteWithChildren = AuthServersRoute._addFileChildren(
  AuthServersRouteChildren,
)

interface AuthSettingsRouteChildren {
  AuthSettingsMcpRoute: typeof AuthSettingsMcpRoute
  AuthSettingsSecurityRoute: typeof AuthSettingsSecurityRoute
  AuthSettingsProfileRoute: typeof AuthSettingsProfileRoute
  AuthSettingsGeneralRoute: typeof AuthSettingsGeneralRoute
  AuthSettingsSmtpRoute: typeof AuthSettingsSmtpRoute
  AuthSettingsNotificationsRoute: typeof AuthSettingsNotificationsRoute
  AuthSettingsAccessRoute: typeof AuthSettingsAccessRoute
  AuthSettingsStorageRoute: typeof AuthSettingsStorageRoute
  AuthSettingsBrandingRoute: typeof AuthSettingsBrandingRoute
  AuthSettingsDnsRoute: typeof AuthSettingsDnsRoute
  AuthSettingsDefaultsRoute: typeof AuthSettingsDefaultsRoute
  AuthSettingsSecurityPolicyRoute: typeof AuthSettingsSecurityPolicyRoute
}

const AuthSettingsRouteChildren: AuthSettingsRouteChildren = {
  AuthSettingsMcpRoute: AuthSettingsMcpRoute,
  AuthSettingsSecurityRoute: AuthSettingsSecurityRoute,
  AuthSettingsProfileRoute: AuthSettingsProfileRoute,
  AuthSettingsGeneralRoute: AuthSettingsGeneralRoute,
  AuthSettingsSmtpRoute: AuthSettingsSmtpRoute,
  AuthSettingsNotificationsRoute: AuthSettingsNotificationsRoute,
  AuthSettingsAccessRoute: AuthSettingsAccessRoute,
  AuthSettingsStorageRoute: AuthSettingsStorageRoute,
  AuthSettingsBrandingRoute: AuthSettingsBrandingRoute,
  AuthSettingsDnsRoute: AuthSettingsDnsRoute,
  AuthSettingsDefaultsRoute: AuthSettingsDefaultsRoute,
  AuthSettingsSecurityPolicyRoute: AuthSettingsSecurityPolicyRoute,
}

const AuthSettingsRouteWithChildren = AuthSettingsRoute._addFileChildren(
  AuthSettingsRouteChildren,
)

interface AuthSitesSiteIdRouteChildren {
  AuthSitesSiteIdIndexRoute: typeof AuthSitesSiteIdIndexRoute
  AuthSitesSiteIdDeploymentsRoute: typeof AuthSitesSiteIdDeploymentsRoute
  AuthSitesSiteIdDomainsRoute: typeof AuthSitesSiteIdDomainsRoute
  AuthSitesSiteIdSslRoute: typeof AuthSitesSiteIdSslRoute
  AuthSitesSiteIdDatabasesRoute: typeof AuthSitesSiteIdDatabasesRoute
  AuthSitesSiteIdDaemonsRoute: typeof AuthSitesSiteIdDaemonsRoute
  AuthSitesSiteIdCronRoute: typeof AuthSitesSiteIdCronRoute
  AuthSitesSiteIdLogsRoute: typeof AuthSitesSiteIdLogsRoute
  AuthSitesSiteIdSettingsRoute: typeof AuthSitesSiteIdSettingsRoute
  AuthSitesSiteIdDangerRoute: typeof AuthSitesSiteIdDangerRoute
  AuthSitesSiteIdBackupsRoute: typeof AuthSitesSiteIdBackupsRoute
  AuthSitesSiteIdDnsRoute: typeof AuthSitesSiteIdDnsRoute
  AuthSitesSiteIdPhpRoute: typeof AuthSitesSiteIdPhpRoute
  AuthSitesSiteIdFilesRoute: typeof AuthSitesSiteIdFilesRoute
  AuthSitesSiteIdEmailRoute: typeof AuthSitesSiteIdEmailRoute
  AuthSitesSiteIdAnalyticsRoute: typeof AuthSitesSiteIdAnalyticsRoute
}

const AuthSitesSiteIdRouteChildren: AuthSitesSiteIdRouteChildren = {
  AuthSitesSiteIdIndexRoute: AuthSitesSiteIdIndexRoute,
  AuthSitesSiteIdDeploymentsRoute: AuthSitesSiteIdDeploymentsRoute,
  AuthSitesSiteIdDomainsRoute: AuthSitesSiteIdDomainsRoute,
  AuthSitesSiteIdSslRoute: AuthSitesSiteIdSslRoute,
  AuthSitesSiteIdDatabasesRoute: AuthSitesSiteIdDatabasesRoute,
  AuthSitesSiteIdDaemonsRoute: AuthSitesSiteIdDaemonsRoute,
  AuthSitesSiteIdCronRoute: AuthSitesSiteIdCronRoute,
  AuthSitesSiteIdLogsRoute: AuthSitesSiteIdLogsRoute,
  AuthSitesSiteIdSettingsRoute: AuthSitesSiteIdSettingsRoute,
  AuthSitesSiteIdDangerRoute: AuthSitesSiteIdDangerRoute,
  AuthSitesSiteIdBackupsRoute: AuthSitesSiteIdBackupsRoute,
  AuthSitesSiteIdDnsRoute: AuthSitesSiteIdDnsRoute,
  AuthSitesSiteIdPhpRoute: AuthSitesSiteIdPhpRoute,
  AuthSitesSiteIdFilesRoute: AuthSitesSiteIdFilesRoute,
  AuthSitesSiteIdEmailRoute: AuthSitesSiteIdEmailRoute,
  AuthSitesSiteIdAnalyticsRoute: AuthSitesSiteIdAnalyticsRoute,
}

const AuthSitesSiteIdRouteWithChildren =
  AuthSitesSiteIdRoute._addFileChildren(AuthSitesSiteIdRouteChildren)

interface AuthSitesRouteChildren {
  AuthSitesSiteIdRoute: typeof AuthSitesSiteIdRouteWithChildren
  AuthSitesNewRoute: typeof AuthSitesNewRoute
  AuthSitesIndexRoute: typeof AuthSitesIndexRoute
}

const AuthSitesRouteChildren: AuthSitesRouteChildren = {
  AuthSitesSiteIdRoute: AuthSitesSiteIdRouteWithChildren,
  AuthSitesNewRoute: AuthSitesNewRoute,
  AuthSitesIndexRoute: AuthSitesIndexRoute,
}

const AuthSitesRouteWithChildren = AuthSitesRoute._addFileChildren(
  AuthSitesRouteChildren,
)

interface AuthWordpressInstallIdRouteChildren {
  AuthWordpressInstallIdIndexRoute: typeof AuthWordpressInstallIdIndexRoute
  AuthWordpressInstallIdPluginsRoute: typeof AuthWordpressInstallIdPluginsRoute
  AuthWordpressInstallIdThemesRoute: typeof AuthWordpressInstallIdThemesRoute
  AuthWordpressInstallIdDatabaseRoute: typeof AuthWordpressInstallIdDatabaseRoute
  AuthWordpressInstallIdSecurityRoute: typeof AuthWordpressInstallIdSecurityRoute
  AuthWordpressInstallIdUsersRoute: typeof AuthWordpressInstallIdUsersRoute
  AuthWordpressInstallIdBackupsRoute: typeof AuthWordpressInstallIdBackupsRoute
  AuthWordpressInstallIdSettingsRoute: typeof AuthWordpressInstallIdSettingsRoute
  AuthWordpressInstallIdDangerRoute: typeof AuthWordpressInstallIdDangerRoute
}

const AuthWordpressInstallIdRouteChildren: AuthWordpressInstallIdRouteChildren = {
  AuthWordpressInstallIdIndexRoute: AuthWordpressInstallIdIndexRoute,
  AuthWordpressInstallIdPluginsRoute: AuthWordpressInstallIdPluginsRoute,
  AuthWordpressInstallIdThemesRoute: AuthWordpressInstallIdThemesRoute,
  AuthWordpressInstallIdDatabaseRoute: AuthWordpressInstallIdDatabaseRoute,
  AuthWordpressInstallIdSecurityRoute: AuthWordpressInstallIdSecurityRoute,
  AuthWordpressInstallIdUsersRoute: AuthWordpressInstallIdUsersRoute,
  AuthWordpressInstallIdBackupsRoute: AuthWordpressInstallIdBackupsRoute,
  AuthWordpressInstallIdSettingsRoute: AuthWordpressInstallIdSettingsRoute,
  AuthWordpressInstallIdStagingRoute: AuthWordpressInstallIdStagingRoute,
  AuthWordpressInstallIdDangerRoute: AuthWordpressInstallIdDangerRoute,
}

const AuthWordpressInstallIdRouteWithChildren =
  AuthWordpressInstallIdRoute._addFileChildren(AuthWordpressInstallIdRouteChildren)

interface AuthWordpressRouteChildren {
  AuthWordpressInstallIdRoute: typeof AuthWordpressInstallIdRouteWithChildren
  AuthWordpressIndexRoute: typeof AuthWordpressIndexRoute
}

const AuthWordpressRouteChildren: AuthWordpressRouteChildren = {
  AuthWordpressInstallIdRoute: AuthWordpressInstallIdRouteWithChildren,
  AuthWordpressIndexRoute: AuthWordpressIndexRoute,
}

const AuthWordpressRouteWithChildren = AuthWordpressRoute._addFileChildren(
  AuthWordpressRouteChildren,
)

interface AuthFilesRouteChildren {
  AuthFilesIndexRoute: typeof AuthFilesIndexRoute
  AuthFilesSiteIdRoute: typeof AuthFilesSiteIdRoute
}

const AuthFilesRouteChildren: AuthFilesRouteChildren = {
  AuthFilesIndexRoute: AuthFilesIndexRoute,
  AuthFilesSiteIdRoute: AuthFilesSiteIdRoute,
}

const AuthFilesRouteWithChildren = AuthFilesRoute._addFileChildren(
  AuthFilesRouteChildren,
)

interface AuthRouteChildren {
  AuthAlertsRoute: typeof AuthAlertsRoute
  AuthAuditLogRoute: typeof AuthAuditLogRoute
  AuthBackupsRoute: typeof AuthBackupsRouteWithChildren
  AuthDaemonsRoute: typeof AuthDaemonsRoute
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthDatabaseServersRoute: typeof AuthDatabaseServersRouteWithChildren
  AuthDatabasesRoute: typeof AuthDatabasesRouteWithChildren
  AuthDomainsRoute: typeof AuthDomainsRouteWithChildren
  AuthEditorSiteIdRoute: typeof AuthEditorSiteIdRoute
  AuthFilesRoute: typeof AuthFilesRouteWithChildren
  AuthToolsPhpMyAdminRoute: typeof AuthToolsPhpMyAdminRoute
  AuthMailRoute: typeof AuthMailRouteWithChildren
  AuthOperatorsRoute: typeof AuthOperatorsRoute
  AuthPluginsRoute: typeof AuthPluginsRouteWithChildren
  AuthScheduledTasksRoute: typeof AuthScheduledTasksRoute
  AuthServersRoute: typeof AuthServersRouteWithChildren
  AuthSettingsRoute: typeof AuthSettingsRouteWithChildren
  AuthSitesRoute: typeof AuthSitesRouteWithChildren
  AuthTemplatesRoute: typeof AuthTemplatesRoute
  AuthWordpressRoute: typeof AuthWordpressRouteWithChildren
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAlertsRoute: AuthAlertsRoute,
  AuthAuditLogRoute: AuthAuditLogRoute,
  AuthBackupsRoute: AuthBackupsRouteWithChildren,
  AuthDaemonsRoute: AuthDaemonsRoute,
  AuthDashboardRoute: AuthDashboardRoute,
  AuthDatabaseServersRoute: AuthDatabaseServersRouteWithChildren,
  AuthDatabasesRoute: AuthDatabasesRouteWithChildren,
  AuthDomainsRoute: AuthDomainsRouteWithChildren,
  AuthEditorSiteIdRoute: AuthEditorSiteIdRoute,
  AuthFilesRoute: AuthFilesRouteWithChildren,
  AuthToolsPhpMyAdminRoute: AuthToolsPhpMyAdminRoute,
  AuthMailRoute: AuthMailRouteWithChildren,
  AuthOperatorsRoute: AuthOperatorsRoute,
  AuthPluginsRoute: AuthPluginsRouteWithChildren,
  AuthScheduledTasksRoute: AuthScheduledTasksRoute,
  AuthServersRoute: AuthServersRouteWithChildren,
  AuthSettingsRoute: AuthSettingsRouteWithChildren,
  AuthSitesRoute: AuthSitesRouteWithChildren,
  AuthTemplatesRoute: AuthTemplatesRoute,
  AuthWordpressRoute: AuthWordpressRouteWithChildren,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
